### ISSUE TITLE
Songs are not getting played in the latest version.

### ISSUE THREAD

**Issue by jatinkumar2438** [Sangwan5688/BlackHole#103]
**Describe the bug**
Songs are not getting played after i tried it many times it does load the time stamps of the song but can't play it. Not even the offline music.
But the older version plays the songs, like v1.9.
idk what's the problem in this version. 
Btw great app. 😀

**To Reproduce**
Playing any song, doesn't matter if it's online or offline music. 

**Expected behavior**
Song should be played like in the old version.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung J7 Prime
 - OS: Android 10
 - App Version [e.g. v1.10.1

**App Logs**
If possible please provide app logs here.

**Comment by Sangwan5688** [comment]
Can you provide app logs, please? It will really help.

**Comment by jatinkumar2438** [comment]
> Can you provide app logs, please? It will really help.

How to do that?

**Comment by Sangwan5688** [comment]
You can check online. If you have pc then you will have to use `ADB` to get logs. The command is `adb logcat` you can filter them too. Well, I can't really explain everything just check online.

**Comment by jatinkumar2438** [comment]
> You can check online. If you have pc then you will have to use `ADB` to get logs. The command is `adb logcat` you can filter them too. Well, I can't really explain everything just check online.

Ok i will do it.

**Comment by Sangwan5688** [comment]
The issue was coz of Equalizer added which doesn't support all devices. I have added an option to opt-out of in-app equalizer from settings, which should solves the issue.

**Comment by jatinkumar2438** [comment]
> The issue was coz of Equalizer added which doesn't support all devices. I have added an option to opt-out of in-app equalizer from settings, which should solves the issue.

Yeah that's the issue.
Thanks 
I also mention about low quality thumbanails on songs downlaod.
Can you fix that too.
and also proper tags.
