### ISSUE TITLE
Supabase table error

### ISSUE THREAD

**Issue by Ruslanbek0809** [Sangwan5688/BlackHole#104]
First of all thank you for your open source app. Could you share screenshot of your supabase "Users" table. Cuz i can't create proper table with columns for users. Error is:  invalid input syntax for type bigint: "ec8cb350-0571-11ec-928c-817fc0bcbf39"

**Comment by Sangwan5688** [comment]
Just create following four fields:
`id` (type `uuid`), `name` (type `text`), `accountCreatedOn` (type `text`) and `timeZone` (type `text`)

**Comment by Ruslanbek0809** [comment]
Thanks it worked. But here is question: when i try to delete one row of data it says "can't find primary key" and nothing happens. Why?

**Comment by Sangwan5688** [comment]
Just make sure `id` is the primary key. And you might need to provide that when you delete the row.

**Comment by Ruslanbek0809** [comment]
oh okay. Thanks. It worked bro. Keep it up)
