### ISSUE TITLE
Simple music player

### ISSUE THREAD

**Issue by CRAG666** [Sangwan5688/BlackHole#109]
First of all, its application is spectacular, it is the best of its kind. However I do not require all the other functions related to streaming, I would like to know if there is a possibility that an alternative is developed that is only a music player.

**Comment by Sangwan5688** [comment]
Actually the app was made for streaming itself at the first place. It was later on that I added offline music support. And even more offline music lack a lot of features like playlists and all which are available for streaming. Anyway I have plans to improve it. Now coming over to your question, I can't actually create a new app with only offline music support as of now. But what I can do and I even have plans is to make some options optional (Spotify and YouTube section). That way you can opt out for YouTube and Spotify section. As for home section I won't be able to make it optional as of now. But let's see maybe in future.

**Comment by CRAG666** [comment]
Tranks
