### ISSUE TITLE
RenderFlex overflow error

### ISSUE THREAD

**Issue by Ruslanbek0809** [Sangwan5688/BlackHole#112]
Hi. I am getting overflow error when I try to open PlayerScreen from Miniplayer.

The relevant error-causing widget was
Column
lib\…\Player\audioplayer.dart:919
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#474ab relayoutBoundary=up2 OVERFLOWING
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 63 pixels on the bottom.
The relevant error-causing widget was
Column
lib\…\Player\audioplayer.dart:919
════════════════════════════════════════════════════════════════════════════════

'package:flutter/src/widgets/basic.dart': Failed assertion: line 247 pos 15: 'opacity != null && opacity >= 0.0 && opacity <= 1.0': is not true.
The relevant error-causing widget was
Miniplayer
lib\CustomWidgets\miniplayer.dart:41
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 99207 pixels on the bottom.
The relevant error-causing widget was
Column
lib\…\Home\home.dart:303
════════════════════════════════════════════════════════════════════════════════

**Comment by Sangwan5688** [comment]
Ya, it's coz of miniplayer package. I don't actually know what's the issue in the package code as I just forked and modified it according to my needs. And as it's code is in [different repo](https://github.com/Sangwan5688/miniplayer), I haven't been able to look at it. I will check it and fix the issue or if you are familiar with flutter then you can have a look at it and open PR on it's [repo](https://github.com/Sangwan5688/miniplayer). Anyway, a ticket is already open for this issue #46
