### ISSUE TITLE
Add Equalizer or Bass booster

### ISSUE THREAD

**Issue by IamMrUnknown** [Sangwan5688/BlackHole#113]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IamMrUnknown** [comment]
Please add Equalizer option

**Comment by Sangwan5688** [comment]
There's already a Equalizer there inside app. Although it is very basic but still it is there. And please write issue inside the first comment itself
