### ISSUE TITLE
Results not found

### ISSUE THREAD

**Issue by Seferi** [Sangwan5688/BlackHole#117]
Great app mate. Tho whenever I search an artist and tap his name, I get 'Sorry, Results not found'... What gives?

**Comment by Sangwan5688** [comment]
If you are not from India try using VPN. Check more details here: https://github.com/Sangwan5688/BlackHole/issues/52#issuecomment-894400639

**Comment by MohamedFaraag** [comment]
why youtube Service is not working with me ?
Note : my Country is Egypt

**Comment by MohamedFaraag** [comment]
all things work good but Youtube service not working with me

**Comment by Sangwan5688** [comment]
@MohamedFaraag what's the exact issue? Please create issue related to your problem with some screenshots and other info. If possible, provide app logs too. Anyway, as your problem isn't related to this issue, just create different issue for your problem with more info.
As for @Seferi, I assume using VPN has fixed the issue. So, I'm closing the issue.

**Comment by Seferi** [comment]
Yes mate, it did fix. Thanks a lot.
