### ISSUE TITLE
Play all/shuffle/add to queue option on spotify local or global list

### ISSUE THREAD

**Issue by Gottarocket** [Sangwan5688/BlackHole#119]
**Is your feature request related to a problem? Please describe.**
Spotify local and global option 
**Describe the solution you'd like**
There should be play all or shuffle option but when we click on song it just shows up song and playlists again instead we need all songs to shuffle 
**Describe alternatives you've considered**
Shuffle or play all or add to queue option on local or global so we can hear all songs

**Additional context**
Adding those buttons prevent clicking on song again on songs and going back and doing so on all playlists

**Comment by Sangwan5688** [comment]
Spotify global and local charts are just charts with names. They aren't actual song links or something. What blackhole does is that it takes the top charts from spotifycharts.com, then shows the chart inside app. Now blackhole uses Saavn to play as well as search music. Now when you tap on any song from that chart, blackhole search it on saavn and show the search result. Now, there can be cases when the song is not available on Saavn or something else. Coz of that reason I haven't added direct play option. I can add it but then there will be lot of cases when something else will start playing (mostly for people who aren't from India). I will think of adding direct play option but it won't work as expected for any country except India.

**Comment by Gottarocket** [comment]
Thanks I get that so I suggested shuffle so out of 10 if one plays other song we can skip as it will be on shuffle anyway if its lot of work or causes issue to others no need
