### ISSUE TITLE
Android 11 Song Download Error

### ISSUE THREAD

**Issue by Sangwan5688** [Sangwan5688/BlackHole#12]
Songs not downloading on Android 11. Most likely, there's some storage issue.

**Comment by Sangwan5688** [comment]
Should be fixed with 7920fa8

**Comment by harshkumarkhatri** [comment]
Hey, have started usingt his app recently. I am unable to download any song or the entire playlist.
When i click on download icon, it shows 0% and does not proceed any further even after waiting for a few minutes. Is there something which i missed or is there something breaking in the app?

**Comment by harshkumarkhatri** [comment]
The issue which i mentioned occurs only when i have set a custom location for the download folder and not when the app uses a default location (which is set by the app itself)
