### ISSUE TITLE
Playlist auto-backup feature

### ISSUE THREAD

**Issue by AnonyUnknownTg** [Sangwan5688/BlackHole#121]
### The problem:

Users who have many playlists like me, have to manually export each playlist individually; which is a quite **time consuming**.

### The solution:

An option of **auto-backup** feature would be great which, when enabled, will export all the playlists to a defined storage path; at a _given time interval or at app startup_.

This way, all the playlists will be in sync with the ones on the app, making user experience better.

**Comment by Sangwan5688** [comment]
Ya, as told earlier I will add it soon. I'm thinking about how I should attach all data in one file, which can be used for all platforms. Anyway, I will add it soon, there are other things pending now. Will try to add it soon.

**Comment by Surendrajat** [comment]
@Sangwan5688 it will also be fine if you save data in multiple files in a selected dir. It doesn't matter as long as the app is able to import all in same way.

**Comment by Sangwan5688** [comment]
I have added an auto backup feature. It will automatically backup data to your external storage on every app start and by default it will be off.
