### ISSUE TITLE
Doesn't find songs that have the mp3 extension in capital letters 

### ISSUE THREAD

**Issue by buzzcola3** [Sangwan5688/BlackHole#123]
The app does not find files that have MP3 (Capital) extension

**To Reproduce**
1. Go to 'file manager'
2. change mp3 extension to MP3
3. App doesn't find the song

**Expected behavior**
Finds MP3 files

**Smartphone (please complete the following information):**
 - Device: mi mix 2s
 - OS: [crDroid Android 11]
 - App Version 1.10.1

**Comment by Sangwan5688** [comment]
I have already changed the way my music section loads songs. It's still on beta channel though, but ya it is fixed. Now, BlackHole will show all type of music files stored on your device. As this is no longer an issue, I'm closing it.
Thanks for using BlackHole :)
