### ISSUE TITLE
Submit in F-Droid

### ISSUE THREAD

**Issue by TheEvilSkeleton** [Sangwan5688/BlackHole#13]
Hi, 

Can this be submitted in F-Droid? F-Droid is an free software and decentralized alternative to Google Play Store. Everything is compiled by the F-Droid team and redistributed via a client.

Here is how to submit: https://gitlab.com/fdroid/rfp/-/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D=#

**Comment by Sangwan5688** [comment]
If it's about the app update, I would like to tell you that the app handles the update feature itself. It will notify the user whenever a new update will be available. Anyway I would have a look and would try to do so.

**Comment by Sangwan5688** [comment]
I went through the procedure and looked over their inclusion policy. Their inclusion policy states that they can't build an app that uses Firebase Analytics, Database, etc. Removing Firebase Analytics isn't much of an issue for me. But I can't remove the database. The app updates, playlists on the home screen, etc., use the database. Even in the future, I plan to provide music recommendations based on recent songs, online upload of user playlists, etc., which need the firebase. So, it is currently not possible to upload the app on F-Droid.
I am closing the issue for now. If you have anything else regarding the issue, feel free to open it again.

**Comment by evrifaessa** [comment]
Just wanted to leave my comment, it'd be awesome to see this app in F-Droid. Thanks for your work :)

**Comment by eternaltyro** [comment]
@Sangwan5688 I don't think having a database is a deal-breaker. Can you point to the resource that mentions this?

Also, the point of F-Droid is not to keep the app updated. It's about trust. I know and trust many developers to do the right thing when packaging their apps. But that doesn't mean I wouldn't like a through review of the claims anyway by a trusted third-party. In this case, it's F-Droid. 

F-Droid has a set of processes that make it very difficult to sneak in malicious code (by intent or accident) and it's a viable alternative to those that don't trust the Google Play Services rootkit.

So I urge you to please reconsider submitting to F-Droid. 

If not, there's a slightly policy-relaxed - but also popular - repository run by IzzyOnDroid (https://apt.izzysoft.de/fdroid/index/info) that will likely take in this app until you sort F-Droid out.

**Comment by Sangwan5688** [comment]
@eternaltyro Ok, I will try submitting it on F-Droid.

**Comment by Sangwan5688** [comment]
Well, it took some time but finally, the request is merged to F-droid data :) It might take some time for the app to actually show up on F-droid depending upon their update cycle (maybe 3-4 days), but the app request has been merged. So, I guess it's time to close the issue.
Thanks and Congrats to everyone out there :)
