### ISSUE TITLE
Fdroid update delay

### ISSUE THREAD

**Issue by saurabhinabys** [Sangwan5688/BlackHole#138]
I've already donated a miniscule amount, and intend to do so regularly. I just hope that F-droid builds get updated as quickly as new versions are released.

**Comment by Sangwan5688** [comment]
See I can't do anything about F-Droid builds. It's not me who posts updates late. It's just F-droid which takes time to update it in their database. F-droid has large collection of apps. They go through update cycle once a week or so. So, it all depends on your update cycle. If you have complains about that do so on F-droid, I can't do anything about that
