### ISSUE TITLE
Next Song/ Play albums not working. 

### ISSUE THREAD

**Issue by tiniwings** [Sangwan5688/BlackHole#14]
Provide option to play all the songs in "Weekly top songs"/“Chart busters“

Currently only one song plays and when I click next song nothing happens.

**Comment by Sangwan5688** [comment]
It shouldn't happen but can you please answer the following questions:
1. Is it happening only in online play or offline play too?
2. When the song completes does it automatically skip to the next one? in both online and offline?
3. Can you provide app logs?

**Comment by Sangwan5688** [comment]
@ntbk1919 It will be confusing if I start explaining here. You can google it. You will find a lot of resources like: https://www.hexnode.com/mobile-device-management/help/obtain-android-device-logs-using-windows-and-mac/
You can even search on youtube or something that would be much easier to understand.

**Comment by Sangwan5688** [comment]
More information is needed regarding the issue. If anyone is facing the same issue please consider commenting so that I can look over the issue. If there's no response from anyone, I might close the issue considering it already solved.

**Comment by Sangwan5688** [comment]
As there hasn't been any update, I am closing the issue, considering it resolved. If anyone encounters the issue, feel free to open it again.
