### ISSUE TITLE
Bug and UI Improvements 💡

### ISSUE THREAD

**Issue by dhishkyaon** [Sangwan5688/BlackHole#142]
**Bug** - Sometimes single tap doesn't open full screen player.

![IMG_20211011_110929.jpg](https://user-images.githubusercontent.com/88529066/136739283-915956c8-89c4-480c-b293-fbed87e4f9e7.jpg)

**UI  Improvements** - 

**_1_**. Mini player is too big and takes more space then required and should use dominant colour like this 👇🏾

![IMG_20211011_111928.jpg](https://user-images.githubusercontent.com/88529066/136739511-9d2ef380-995e-4df3-aa9d-44dcbc01768c.jpg)

**_2_**. Give an option to turn on/off gradient on dominant colour for play screen or turn it off by default.

**_3_**. Turn off functionality to change volume level from play screen because imo its useless. No one is going to change volume levels from it instead of using physical buttons. And also its annoying because each time i am minimizing the player i have to carefully set my thumb outside that poster box 😂

**_4_**. Close 'Now Playing' section with swipe down on it after reaching top of the list just like full screen player.

**_5_**. Show bottom nevigation bar, even after opening any album or playlist.

**_I know these are too much requests from my side but i just want to provide feedback. 😁_**

Thanks ❤️

**Comment by Sangwan5688** [comment]
I'm not sure about that bug. It works perfectly for me. I will look deeper if I receive more bugs reports regarding that. As for other features, I will try to add as many as possible.

**Comment by dhishkyaon** [comment]
5. okay, but you can redefine the transition atleast.

**Comment by Sangwan5688** [comment]
Hmmm, will ya I can change transitions. I will try using some and will change it wherever necessary.

**Comment by SkyWalker1005** [comment]
Here is one UI issue in playlist menu.
![Screenshot_20211105-093517_BlackHole.png](https://user-images.githubusercontent.com/48923623/140456788-4487a885-dc04-4d74-a061-9b615ad00944.png)

Top sticky bar is overlapping the heading text. Let me know if need to raise this in another thread.

**Comment by Sangwan5688** [comment]
@SkyWalker1005 ya you can raise this in another thread as this one's not related to that

**Comment by dhruvanbhalara** [comment]
Duplicate https://github.com/Sangwan5688/BlackHole/issues/177
