### ISSUE TITLE
Android Auto implementation

### ISSUE THREAD

**Issue by zachvlat** [Sangwan5688/BlackHole#143]
It would be nice if blackhole had an Android Auto implementation like [Voice](https://github.com/PaulWoitaschek/Voice).

**Comment by Sangwan5688** [comment]
Ok, so as I don't have anything to test, I need more info regarding this issue, like what exactly is working and what's not.

**Comment by Sangwan5688** [comment]
Closed with #582

**Comment by Fauzdar1** [comment]
Still can't use Blackhole with Android Auto, has anyone even tested it?

**Comment by mrid88** [comment]
There's no search option in blackhole when connected to Android auto
