### ISSUE TITLE
Save themes

### ISSUE THREAD

**Issue by lastra-dev** [Sangwan5688/BlackHole#146]
I'm always changing themes and I have the need to go back to the ones that I like.
For this I'd like to be able to save and load the themes that I make.

Since it's not a very complicated task (because everything is already built for it, thanks to you) i'm already working on it, but I'm making this issue to ask if this is a feature you'd like to have.

<img src="https://i.imgur.com/fxvacD3.png" alt="Theme Selector" width=250>

(Notice the "Save Theme" and "Current Theme" options)

**Comment by lastra-dev** [comment]
Ok, so I already did the PR, go check it out #147

**Comment by Sangwan5688** [comment]
Hmmm it sounds cool. You have added a button to save theme but how to remove that saved theme?? I think there's no button to delete a saved theme. I haven't checked the PR yet will check the code after sometime and let you know other changes too.
Thanks for contribution :)

**Comment by lastra-dev** [comment]
Closing this issue since PR #147 is merged, thanks!
