### ISSUE TITLE
App compatibility with Android 12

### ISSUE THREAD

**Issue by shubham8499** [Sangwan5688/BlackHole#152]
Hey,I really like this app and have donated also to keep u motivated in your work.
But recently I have upgraded to android 12 ,
This app gets installed on android 12 and even opens and download songs.but if we hit play it doesn't stream or play the song.
It would be really helpful if u add android 12 compatibility for your amazing app.

**Comment by Sangwan5688** [comment]
@shubham8499 just wanted to confirm if you are using any custom A12 Rom?? If yes then there might be a case that your custom rom have some issues related to Equalizer. The app works fine on Android12. Just try turning off Equalizer from app settings and check if it's working or not. Do restart the app after changing that.

**Comment by Sangwan5688** [comment]
I have upgraded compile sdk version in afa9633

**Comment by buzzcola3** [comment]
@Sangwan5688 I'm using the compiled AOSP 12. 
(Mine is an early build from around October 10 source)
Pretty sure there is no custom EQ there. 
Logcat (Logcat Reader app):

[logcat_11-08-2021_00-16-48.txt](https://github.com/Sangwan5688/BlackHole/files/7526250/logcat_11-08-2021_00-16-48.txt)

![Screenshot_20211112-101457](https://user-images.githubusercontent.com/31044374/141442106-3d75b81f-374c-41e4-81cb-0fd0bf95fad3.png)

**Comment by Sangwan5688** [comment]
@buzzcola3 From logs it looks like it's equalizer issue. Go to app settings and turn off equalizer. It will work fine then. (refer to #174)
