### ISSUE TITLE
Unable to play songs from youtube 

### ISSUE THREAD

**Issue by Livewire13** [Sangwan5688/BlackHole#157]
**Unable to play any song from youtube**

**Behavior:**
1. Search for youtube song in youtube tab
2. Song plays for first time and works without any issue
3. after sometime when song is played again it skips to the next song (i assume its not able to find the stream)

**Expected behavior:**
Song should be able to play without skipping to the next song 

**Smartphone details:**
 - Device: Asus zenfone max pro
 - OS: Android 10
 - App Version v1.11.0

**Note:**
I have disabled adblocker and it still doesnt work. I assume it is not able to find the youtube stream to play the song. All the songs from saavn plays properly

**Comment by Sangwan5688** [comment]
Ya, so I will work on that part in future. As of now youtube links expire after a particular time interval (mostly 1 day). Coz of that you can't actually play same song from same url. And as the app fails to play song from that url it just skips it.
As there's already a ticket open for this issue (#148), I will be closing this one. If you have any comments or something else related to this issue, please continue it in #148.
