### ISSUE TITLE
sir, can you add play next or add to queue options in youtube search

### ISSUE THREAD

**Issue by fabtune** [Sangwan5688/BlackHole#158]

**Comment by Sangwan5688** [comment]
Umm well, technically it's possible. The only reason why I haven't added those options is coz right now getting audio link of those youtube videos takes some time (as you might have seen while playing those songs). I have some workaround in my mind as of now. First of all, I will add these add to queue and all for youtube videos. It will take some time to add them to queue but I hope that's not a big concern coz they are gonna play later on.
Now about playing playlists and all, only one song is loaded as of now. I'm thinking to add a function to get link of all songs one by one and then add them to queue. It will be little slow as it takes a significant time to get those links.

**Comment by fabtune** [comment]
thankyou, 
so can you make direct download button in youtube search screen like home screen search,
its easy to download songs from youtube
