### ISSUE TITLE
Importing playlist from spotify crashes

### ISSUE THREAD

**Issue by Avendo07** [Sangwan5688/BlackHole#161]
**Describe the bug**
Importing playlist list throws an error. It goes blank after a certain list item.

I checked the issue and the problem is that one of the playlists did not have any item in the images array from the spotify api, and thus it crashes. I think adding a placeholder image there should do it.

**Screenshots**
![Screenshot_20211031_195759](https://user-images.githubusercontent.com/43928724/139588499-f5ae6a09-9b33-4845-b4ed-64c8237c306e.png)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10
 - OS: Android 11
 - App Version - v 1.11.0

**App Logs**
- Logs from android studio

======== Exception caught by widgets library =======================================================
The following RangeError was thrown building:
RangeError (index): Invalid value: Valid value range is empty: 0

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      fetchPlaylists.<anonymous closure>.<anonymous closure> (package:blackhole/Screens/Library/playlists.dart:628:144)
#2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:456:22)
#3      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1214:28)
#4      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1227:55)
#5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2573:19)
#6      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1220:12)
#7      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#8      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1968:59)
#9      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:916:15)
#10     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1968:14)
#11     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
#12     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:484:5)
#13     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:239:19)
#14     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:282:12)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#16     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#20     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1923:12)
#21     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1881:20)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#38     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#42     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#46     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#51     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1388:11)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#55     RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:1359:14)
#56     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1713:7)
#57     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885:18)
#58     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
#59     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#60     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#61     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#62     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#63     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#67     _invoke (dart:ui/hooks.dart:166:10)
#68     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#69     _drawFrame (dart:ui/hooks.dart:129:31)

**Comment by Sangwan5688** [comment]
As far as i remember, the app does check for image list and returns an empty image in this particular case. Are you sure you are using latest code?? Anyway, I will again check the code and let you know
