### ISSUE TITLE
[NowPlaying] [MRNowPlaying] Ignoring setPlaybackState because application does not contain entitlement com.apple.mediaremote.set-playback-state for platform

### ISSUE THREAD

**Issue by BechirAhmed** [Sangwan5688/BlackHole#162]
**Describe the bug**
[NowPlaying] [MRNowPlaying] Ignoring setPlaybackState because application does not contain entitlement com.apple.mediaremote.set-playback-state for platform

This issue killed me,I've searched everywhere .

**To Reproduce**
Click any song to play

**Smartphone (please complete the following information):**
 - Device:iPhone xs max
 - OS: IOS 15
 - App Version [e.g. v1.5]

**App Logs**
======== Exception caught by widgets library =======================================================
```
The following NoSuchMethodError was thrown building StreamBuilder<PlaybackState>(dirty, state: _StreamBuilderBaseState<PlaybackState, AsyncSnapshot<PlaybackState>>#5610d):
The getter 'processingState' was called on null.
Receiver: null
Tried calling: processingState

The relevant error-causing widget was: 
  StreamBuilder<PlaybackState> file:///Users/admin/bech/ilhewl/ilhewl/lib/Screens/Player/audioplayer.dart:773:20
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      ControlButtons.build.<anonymous closure> (package:ilhewl/Screens/Player/audioplayer.dart:777:57)
#2      StreamBuilder.build (package:flutter/src/widgets/async.dart:546:81)
#3      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:124:48)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
...
====================================================================================================
[NowPlaying] [MRNowPlaying] Ignoring setPlaybackState because application does not contain entitlement com.apple.mediaremote.set-playback-state for platform
```

**Comment by Sangwan5688** [comment]
Well, I'm not really sure about iOS Side. But going through logs it looks like the Processing State Stream is returning null and there's `NoSuchMethodError`. So, I assume this method it's not supported in iOS in the package. You will either have to find a workaround or remove this particular feature for iOS.

**Comment by radughitescu** [comment]
I'm also having this issue and investigating but to no avail for the moment

**Comment by Sangwan5688** [comment]
Ok, So thanks to @BechirAhmed for pointing out that playback works fine on stopping the audioHandler before playing any song. I don't know why it works but well as long as it works its fine. So I assume this issue is no longer valid and hence closing it.
