### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by Fernando321438** [Sangwan5688/BlackHole#167]
does anyone know how or what could be changed to make the audio go on IOS?

**Comment by Sangwan5688** [comment]
As of now, app officially doesn't support iOS. There are a few users who have edited code a bit so as to make it work on iOS. You can do the same if you know coding. As for guidelines, I'm not really sure what you will have to do.
And please continue any discussion related to iOS in #42

**Comment by Fernando321438** [comment]
Can you roughly know what needs to be changed in the code to make it work?

**Comment by Sangwan5688** [comment]
Nope, not really sure. You will have to try urself

**Comment by BechirAhmed** [comment]
@Fernando321438 what issues you get? show some code or logs to help you play songs in IOS

**Comment by Fernando321438** [comment]
@BechirAhmed The problem is that it doesn't give me any errors on the code. The app just crashes when I hit a song to play it
