### ISSUE TITLE
Import Playlist from YouTube not working

### ISSUE THREAD

**Issue by le-corbeau** [Sangwan5688/BlackHole#172]
While importing a playlist from YouTube, the app doesn't add the correct tracks to the playlist. Some titles have similar titles but others seem completely unrelated.

Steps to reproduce:
1. Copy playlist URL from YouTube app ( in my case: https://youtube.com/playlist?list=PLryjiIdyiLonfYa9isV9wY6FH8zAqLBf0)
2. Go to Blackhole (ver. 1.12.0) -> Library -> Playlist -> Import from YouTube
3. Paste playlist URL

Importing the below playlist in the app results in the playlist in the attached screenshot:
https://youtube.com/playlist?list=PLryjiIdyiLonfYa9isV9wY6FH8zAqLBf0

![Screenshot_20211108-201311](https://user-images.githubusercontent.com/19852921/140762291-447e8c21-1547-478a-857f-b711d0960b92.jpg)

**Comment by Sangwan5688** [comment]
Refer to #173 I have explained everything there
