### ISSUE TITLE
Spotify/YouTube import not working properly

### ISSUE THREAD

**Issue by JOJOVAV** [Sangwan5688/BlackHole#173]
**Describe the bug**

**To Reproduce**
1. Open the app
2. Click on library tab
3. Go to playlist
4. Log in spotify
5. Choose your playlist
6. wait till it's imported and compare the songs from the playlist

**Expected behavior**
I expected to have all the right songs you can listen to

**Screenshots**
https://i.imgur.com/ecIomJj.png

https://media.discordapp.net/attachments/907332831271870514/907332863224053770/Screenshot_20211108-191329.png?width=311&height=674

https://media.discordapp.net/attachments/907332831271870514/907332862821425192/Screenshot_20211108-191324.png?width=311&height=674

**Smartphone (please complete the following information):**
 - Device: [Nokia 7.2]
 - OS: [Android 10]
 - App Version [V1.12.0]

**App Logs**
If possible please provide app logs here.

**Comment by Sangwan5688** [comment]
BlackHole don't actually use spotify to play songs. The backend used inside blackhole is JioSaavn (A popular Indian Streaming Service). So, when you import playlists from spotify or youtube what actually happens is that blackhole takes the song name from spotify/youtube and then search it on JioSaavn. The top search result is then added to your playlist inside BlackHole.
Now, 3 things can happen while importing playlists:
1. The song which was in your spotify playlist, shows up as the top result on JioSaavn. So right song will be addded.
2. The song which was in your spotify playlist doesn't show up at top. So, some other song which is showing at top will get added
3. No search results are found for that song, so nothing gets added for that particular song (it skips that song).

So, how can we make sure that the song which we want show up on top of search results and gets added.
Here're a few tips:
1. If you are not from India, use a VPN with Indian Server. Search results show random stuff when accessed outside India (refer to this #52). You don't need VPN for everything. Just for search results and things which depend upon search result (i.e. spotify & youtube import)
2. Make sure you select proper music language in app settings. Let's say you want to import a playlist with English songs. So only choose English as your music language in app settings. Don't keep English and Hindi both. Search results vary according to your seleccted music language.

After doing these 2 things, if you are importing an English Playlist with common popular songs, then about 90% of songs will be imported correctly. After importing you can manually try searching a few songs and see if JioSaavn actually has those songs or not.
Also, I see that you are trying to import a playlist which has songs specific to one particular artist. You can just try searching that artist. I can see it is there. (Just make sure to use VPN with Indian Server)

**Comment by spotted-cat** [comment]
@Sangwan5688 Isn't there a better way to search songs ? and to make sure that the matches are 100% correct ?

**Comment by Sangwan5688** [comment]
See the api is highly dependent on your ip address. And it's not my api so I can't do anything to fix that issue.

**Comment by AkhilendraAlle** [comment]
Do we have any feature or mechanism for auto updating / refreshing the Playlists which was imported from YouTube playlist ?

**Comment by JoshuaZXL1** [comment]
just get poweramp works alot better than blackhole

**Comment by ihos28** [comment]
Same problem with the import of Spotify at the end are all indian songs not my music list from Spotify

**Comment by ihos28** [comment]
I have English language set

**Comment by ihos28** [comment]
![Uploading Screenshot_20230622_154130.jpg…]()

**Comment by ihos28** [comment]
![Uploading Screenshot_20230622_154130.jpg…]()
