### ISSUE TITLE
Add Korean and Japanese languages in `Music & Playback`

### ISSUE THREAD

**Issue by BreadGenie** [Sangwan5688/BlackHole#175]
The options in music languages are limited to English and Indian languages (which I'm not a fan of) so adding Korean and Japanese would be nice.
Thanks for the cool app.

**Comment by BreadGenie** [comment]
is it maybe limited due to JioSaavn?

**Comment by Sangwan5688** [comment]
Actually BlackHole uses JioSaavn in it's home section, which is an Indian Streaming Service and has only these languages which are inside the app. So it's not really possible for me to add other languages.

**Comment by BreadGenie** [comment]
That's unfortunate. Thanks for the response.
