### ISSUE TITLE
Rearrange categories at home screen

### ISSUE THREAD

**Issue by dhishkyaon** [Sangwan5688/BlackHole#178]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Give an option to rearrange categories available at home screen.

**Describe alternatives you've considered**
Nothing

**Additional context**
Something like this -

![IMG_20211114_143137.jpg](https://user-images.githubusercontent.com/88529066/141674552-771704df-419b-4002-8c36-112a8cae8301.jpg)

**Comment by atharv2348** [comment]
Could you please explain the issue? @dhishkyaon
