### ISSUE TITLE
A bunch of bugs in V1.12.0 

### ISSUE THREAD

**Issue by mwolfyy** [Sangwan5688/BlackHole#179]
**Describe the bug**
The Home page doesn't load/play and etc. any music, exept this from India.
Tried with the VPN feature, nothing happens.
Also, the YT playlist is breaking the playlists after an import.

**To Reproduce**
1. Go to 'Home Screen'
2. Click on 'Search tab' > Write 'Eminem' (for example) > try to play it.
Second bug:
1. Go to 'Library' > 'Playlists' > 'Import from YouTube' > and enter a random playlist from YT, it doesn't matter. > Wait to load them, and to make the playlist > open the playlist thats created > see whats in there.

**Expected behavior**

**Screenshots**
I cannot attach them, sorry.

**Smartphone (please complete the following information):**
 - Device: Huawei P40 Lite E
 - OS: Android 10
 - App Version Lastest (1.12.0)

**Comment by Sangwan5688** [comment]
Refer to #52 & #173

**Comment by Sangwan5688** [comment]
As I said in last comment these are coz of your region. If you are not from India then use any vpn with Indian Server. It will solve these issues. As these issues are already addressed in other issues (mentioned in above comment), I'm closing this issue.
