### ISSUE TITLE
Not all offline songs are playing

### ISSUE THREAD

**Issue by asifmhdashik** [Sangwan5688/BlackHole#18]
Not all offline songs are playing and offline audios and songs which are downloaded from other sources are also not being played.It must be happening because of not having the song's Info like - Proper Song Name, artist name ,etc.

**Comment by Sangwan5688** [comment]
Can you please provide the app log or any reproducible example so that I can look into the matter? About playing songs from other sources, the app should play a song no matter where it's downloaded from, and even if there's no metadata (title, artist name, etc)

**Comment by asifmhdashik** [comment]
This is what I got as app log when I tried to access a song named .And are not playing after a certain index like for me after 18 songs,The rest are not playing and giving this log. SugarCrash! - ElYotto.m4a and this song was downloaded using the app .
![Screenshot 2021-05-12 at 8 11 28 PM](https://user-images.githubusercontent.com/76432849/117994570-458b8000-b35e-11eb-9998-8c3a5fcb1203.png)

**Comment by Sangwan5688** [comment]
You got this error while playing offline music?? I don't think such an error can occur during playing. What were you playing? Can you provide more details? I assume you build the app using code and then got these logs. So there might be indications like where the error is and all that.

**Comment by asifmhdashik** [comment]
Can this help 
![Screenshot 2021-05-14 at 1 22 11 PM](https://user-images.githubusercontent.com/76432849/118240577-c9f21600-b4b8-11eb-852a-a036d60040eb.png)
![Screenshot 2021-05-14 at 1 22 57 PM](https://user-images.githubusercontent.com/76432849/118240588-cd859d00-b4b8-11eb-939f-230090886dbd.png)

**Comment by Sangwan5688** [comment]
I assume there's a Whatsapp audio that you are trying to play and it is causing the issue. Looks like something is wrong with the audio file and the player is unable to read it. Ok, I will have a look and will try to skip such audio files.

**Comment by asifmhdashik** [comment]
I tried deleting this specific file then got to know that the local songs list is not getting  updated when an audio is deleted. And I deleted a duplicated song but this was also not updated in the songs list.And even tried clearing the user data.

**Comment by Sangwan5688** [comment]
"My Music" Songs are updated every time you open the "My Music" tab. If you are still seeing audio then it means it's not deleted. There might be a chance that there are multiple audios with the same name. That might be the reason you are still seeing the audio even though you deleted one.
What you can do is just try deleting any song from the "Music" folder or from "Downloads" and check if it's still showing. Most probably it won't show there. Also, do close the "My Music" tab and open it again to see the updated list as it's only updated when you open "My Music".

**Comment by asifmhdashik** [comment]
@Sangwan5688 am sorry you were right,The songs were just moved to bin and not deleted.And For me not just WhatsApp audio was not playing but some other songs too.I downloaded a song from some other source and it  is also not playing.Some other error appears too in the log.
![Screenshot 2021-05-16 at 12 46 04 AM](https://user-images.githubusercontent.com/76432849/118375699-fe60f180-b5e0-11eb-822a-f61f7fdbdb25.png)
![Screenshot 2021-05-16 at 12 46 04 AM](https://user-images.githubusercontent.com/76432849/118375705-03be3c00-b5e1-11eb-8354-43dc0b238ebc.png)

**Comment by Sangwan5688** [comment]
Thanks for all that info. I will resolve the issue soon. One more thing, can you please send those audio files which are causing the issue. It will be a lot of help.

**Comment by asifmhdashik** [comment]
This is a download link for that audio
`https://www.mediafire.com/file/mvdx7u5k4ahfklm/Major_Lazer_and_DJ_Snake_-_Lean_on.mp3/file`

**Comment by Sangwan5688** [comment]
@asifmhdashik It is showing permission denied you can share it via any "contact us" method inside the app settings.

**Comment by asifmhdashik** [comment]
@Sangwan5688 Iwas unable attach the file because it exceeded more 5 mb. I have uploaded the song to Google drive, I belive that you will be download the song from this link.
`https://drive.google.com/file/d/1WLOGYyrX4jtkR4d5pzABBk77-oBkZiCq/view?usp=drivesdk`

**Comment by Sangwan5688** [comment]
I got it and even able to reproduce the issue. I will fix the issue soon. Thanks for your support.

**Comment by Sangwan5688** [comment]
Lemme know if this fixes the issue. If not, feel free to open the issue again.

**Comment by asifmhdashik** [comment]
That music's issue was fixed but there are still songs which are some spam audios and they are not there in my device and it is giving error and  this is breaking the loop again.And some of my WhatsApp audios are also tried to be read and this is giving some errors too

**Comment by Sangwan5688** [comment]
Send those audio files too, I will have a look

**Comment by asifmhdashik** [comment]
I don't have those audio files in my device now ,it must have been some cache left on the device.I was unable the find the song or the directory given In the app log through my file explorer.The songs listed in the app exceeds the no of songs listed in file manager as audio or music.I think the app is digging deep for audios and also trying to read some of the left behind caches songs which were deleted or spam.  
`2021-05-16 23:04:53.022 10996-11183/com.shadow.blackhole E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: Cannot create file, path = '/data/user/0/com.shadow.blackhole/cache/Scream-And-Shout-/ashsongss.blogspot.com/http://ashsongss.blogspot.com.jpg' (OS Error: No such file or directory, errno = 2)
    #0      _File.create.<anonymous closure> (dart:io/file_impl.dart:255:9)
    #1      _rootRunUnary (dart:async/zone.dart:1362:47)
    #2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
    #3      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
    #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
    #5      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
    #6      Future._completeWithValue (dart:async/future_impl.dart:539:5)
    #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:577:7)
    #8      _rootRun (dart:async/zone.dart:1354:13)
    #9      _CustomZone.run (dart:async/zone.dart:1258:19)
    #10     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
    #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
    #12     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
    #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)`

**Comment by Sangwan5688** [comment]
Can you try with the latest commit and lemme know if the problem is happening or not and what error it is giving.

**Comment by asifmhdashik** [comment]
Yes, this issue was solved by the  latest commit.

**Comment by Sangwan5688** [comment]
Ok thanks for letting me know
