### ISSUE TITLE
support for more lyrics + flac support? 

### ISSUE THREAD

**Issue by Relected** [Sangwan5688/BlackHole#182]
I keep finding out that a LOT of songs that definitely has lyrics are not on blackplayer for some reason + there is a good way to download lyrics from sites like deezer and flacs and extra mp3s from [free mp3 download](free-mp3-download.net) and other repositories

**Comment by Sangwan5688** [comment]
I have already added more lyrics support in beta versions. You will be able to see them in next stable. As for Flac, I personally don't have any plan to add them.
