### ISSUE TITLE
Add a feature: Resso Playlist Import

### ISSUE THREAD

**Issue by CodeWithDeepanshu** [Sangwan5688/BlackHole#183]
I just want you to add a feature for adding playlist of **Resso** rest everything is very good in your app

**Comment by Sangwan5688** [comment]
What exactly you mean by playlists of resso? You want app to support import from resso?

**Comment by CodeWithDeepanshu** [comment]
> What exactly you mean by playlists of resso? You want app to support import from resso?

Yes brother...
please add that feature

**Comment by Sangwan5688** [comment]
Does resso has any option to export playlists? And how exactly they export? Is there an option to export as file? Can you share the details about how data is formated in that file?

**Comment by CodeWithDeepanshu** [comment]
> What exactly you mean by playlists of resso? You want app to support import from resso?

In Resso we can't export playlist as in YT Music.

But we can share via link as a sample I'm sharing to you.

https://m.resso.app/ZSeSTPXGq/

Rest you can check

**Comment by CodeWithDeepanshu** [comment]
> These kind of links wont help. I would prefer if you can share it as a file or something which might contain the names of all the songs. If you were to share it as a link and i will have to scrap the website to get all their names and all but is too much of a work.

Do you mean name of all the songs in the playlist

**Comment by Sangwan5688** [comment]
> > These kind of links wont help. I would prefer if you can share it as a file or something which might contain the names of all the songs. If you were to share it as a link and i will have to scrap the website to get all their names and all but is too much of a work.
> 
> Do you mean name of all the songs in the playlist

yup

**Comment by CodeWithDeepanshu** [comment]
Sorry there is no such feature....
But if u want I can create a txt file of all songs in my playlist

**Comment by Sangwan5688** [comment]
Ok, If it doesn't support export as file or something which can provide me with song names then it won't be easy for me to implement it. I will most probably have to scrap their website then which isn't a reliable solution and require a lot of work too.
No, you don't have to create a text file. It's just too much manual work. I will try something

**Comment by CodeWithDeepanshu** [comment]
> Ok, If it doesn't support export as file or something which can provide me with song names then it won't be easy for me to implement it. I will most probably have to scrap their website then which isn't a reliable solution and require a lot of work too. No, you don't have to create a text file. It's just too much manual work. I will try something

Ok and thnx a lot for your help and best service ever in advance

**Comment by ketchup-bro** [comment]
Any progress with this? It's not there anywhere on internet.

**Comment by Sangwan5688** [comment]
@ketchup-bro The only option left as of now is to scrape their website and I'm thinking to do the same. I'm just busy with other stuff so it will take time.

**Comment by ketchup-bro** [comment]
Okay . Yeah take your time. I have found a way how to get the list of songs from website if u want that : via inspect element or convert it into pdf via print friendly chome extension ( and convert it into only text )  or text grabber . This gives us for the list of all songs and singers .

**Comment by Sangwan5688** [comment]
Ya, I do know how to scrape. So that's not a problem. But it would have been much easier if there were any other export option in resso. Anyway, no issues

**Comment by ketchup-bro** [comment]
Wish you the best bro. Can you just help me get the list of songs without singers for a url ? What i am planning is will convert it into a youtube playlist by giving in the song list and download that.

**Comment by Sangwan5688** [comment]
`https://api.resso.app/resso/playlist/detail?device_platform=web&sim_region=in&playlist_id=6942819720509790209`
This is the api used inside resso and same can be used to get all tracks. Just change the playlist_id at the end to the one provided by the user.

**Comment by ketchup-bro** [comment]
Thanks for the help. I really appreciate that bro.

**Comment by baduseruyir** [comment]
You can get .txt file by requesting account info in privacy option

**Comment by oceantsunami** [comment]
I'm trying to get the files now, but not being able . Should have done it earlier as I was having a bad premonition.
