### ISSUE TITLE
changing how the file is named by default

### ISSUE THREAD

**Issue by Relected** [Sangwan5688/BlackHole#187]
whenever I download a song using blackplayer the file name is always %title -  %artists

I would like to have the option so that files downloaded by default would have a custom prefix-suffix like %artist - %title or something like that

Also why are the music downloaded in m4a format instead of mp3? the file is not truly 320kbps

**Comment by Relected** [comment]
@Sangwan5688 I know that m4 is better, but it's not as widely used and supported as mp3 + the 320kbps m4a files that are downloaded arent actually 320kbps

I knew this after running an mp3 320kbps from soundcloud and the m4a 320kbps version from blackplayer on a spectogram app (aspect pro) , and apparently the mp3 from SoundCloud was capped at 20k but the m4a was capped at 16k

the song was: Moxifloxi - Ghost

**Comment by Sangwan5688** [comment]
See streaming apps don't use mp3. All streams app use m4a or opus afaik. And most devices support m4a now a days. There are some other reasons too. First of all I'm receiving m4a files directly. If I were to provide mp3, I would have to convert them using ffmpeg or something. I personally don't want to add ffmpeg coz it will increase app size a lot. Finally, about quality I don't have quality or anything in my hand. They are directly taken from JioSaavn. But it's not like they aren't 320. But ya there's a slight variation like some are lower than 320kbps whereas some are above 320kbps. They are not forced to be exactly 320 kbps.
