### ISSUE TITLE
Translation on TWO weblate instances ?

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Sangwan5688/BlackHole#188]
i found it on [weblate.bubu](https://weblate.bubu1.eu/projects/blackhole/)AND on [hosted.weblate](https://hosted.weblate.org/projects/blackhole/localization/)

Now I am confused. 
Isn't that enough on one instance? Couldn't you then delete the second one?

**Comment by Sangwan5688** [comment]
Oh ya use the hosted one. I will delete the other one.
