### ISSUE TITLE
Sorting options

### ISSUE THREAD

**Issue by FindMalek** [Sangwan5688/BlackHole#194]
Hey!
There's a feature I'd like to request. It's the sorting of the songs in a playlist, In the app there's only 3 types of sorting "A-Z" "Z-A" and "Last Added".
May you add a new one, It's the sorting by Album and sorting by Artist.

Thank you!

**Comment by Sangwan5688** [comment]
These have been already added in beta release. You can try beta version if you are on telegram otherwise wait for it to come to stable.
