### ISSUE TITLE
Landscape mode doesn't scale correctly to iPads. 

### ISSUE THREAD

**Issue by CommanderEntropy** [Sangwan5688/BlackHole#198]
**Describe the bug**
The music player when maximised and put in landscape does not scale correctly to iPads. This may be an issue only present on 9.7" and smaller iPads and may not be present on larger ones. 

**To Reproduce**
1. Play a song
2. Click on the mini player to maximise it
3. Put the device in landscape

**Expected behavior**
The album art and controls scale correctly. 

**Screenshots**
![Broken Landscape.PNG](https://user-images.githubusercontent.com/83172580/147198799-fb720fe6-36be-48b4-baa3-6fa523ba88f8.PNG)

**Smartphone (please complete the following information):**
 - Device: iPad Air 1
 - OS: iOS 12.5.5
 - App Version: v12.2.2

**Comment by Sangwan5688** [comment]
Ya, so this issue has already been fixed. As I was building the app for windows I faced this issue and hence even fixed it. It's still not there in the ipa file, as that ipa file is an old one. If you have mac and other requirements to build it yourself, you can clone repo and do so. Or you can just wait for next ipa file.
Anyway, as It's already fixed I'm closing this.
