### ISSUE TITLE
Infinite search spinner when searching an unmatched song.

### ISSUE THREAD

**Issue by atsigkas** [Sangwan5688/BlackHole#20]
In the search section (songs,artists or podcasts), when an unmatched song (by name) is setted to search,
the searching doesn't stop and you are left with an infinite search spinner in the screen.  
You can take a look on the screenshot below :
![185108402_138920381554710_5213095648679638338_n](https://user-images.githubusercontent.com/38073192/118027686-dff1c080-b36a-11eb-99de-ad7bdd59cc1e.jpg)

**Comment by Sangwan5688** [comment]
What you searched for?

**Comment by atsigkas** [comment]
@Sangwan5688 
yeah , it keeps spinning for ever . 
Basically to be more specific , 3/4 (tries) it keeps spinning and the 1/4 after a few seconds it lets you with an blank screen . 
I tried it and with other songs to be sure and the results it's almost the same , almost half of the times it lefts you with an i infinite spinner . 

Could this be a bug ? 

Maybe if we could remove spinner after a set of time ,populate a message on the screen like : 
'The song name doesn't mutch'
and after than make a return to the previous state ??

**Comment by Sangwan5688** [comment]
There were some songs that were causing the issue. I fixed it and have already committed the changes. As I can't make a new release for every single bug, I haven't released the app. You will see the changes reflected in the next version. If you want, you can build your own app before that using the code.

**Comment by atsigkas** [comment]
So due to debug this , you propose me to built my own app with same code till now and try to fix it in this way  ?

**Comment by Sangwan5688** [comment]
I have already fixed it and made changes to the code. But as v1.5 is already released and I don't want to release a new version for every little bug so these changes will come in v1.6. That's what I'm trying to say. And if you don't want to wait for v1.6 you can download the code and build your own app. I hope you get it now.

**Comment by atsigkas** [comment]
yeah, now it's understood ! :D 
Do you suggest me a spesific developer platform that is more preferable , to work into?

**Comment by Sangwan5688** [comment]
You mean like google colab? If you aren't familiar with flutter and how to build apk then just wait for the next version. Otherwise, you can download flutter, install dependencies and build using "flutter build apk" from any code editor you use. To know more about how to build you can google it. Also, the version build from the code will be a bit different from the one released. The released one is for common users and has a different database. So I would suggest just wait for v1.6.
