### ISSUE TITLE
Equilizer

### ISSUE THREAD

**Issue by Yash071goel** [Sangwan5688/BlackHole#202]
In this update Equlizer not show fix please

**Comment by Sangwan5688** [comment]
You will have to turn it on from "Settings". There's an option there something like "Use Equalizer" or something. The reason I turned it off by default was coz some users face issue like song not playing coz their device doesn't support equalizer provided within app. So user had to turn off equalizer from app settings to make it work and like not everyone knows about that. So, I just turned it off by default.
Anyway, as there's no such bug I'm closing the issue
