### ISSUE TITLE
Explain where music is coming from

### ISSUE THREAD

**Issue by gringofe** [Sangwan5688/BlackHole#203]
**Is your feature request related to a problem? Please describe.**
Your music player makes it seem like the streaming function is using Spotify (there is a tab called `Spotify Charts`, and clicking on a song starts playback), but the songs are actually loaded from https://www.jiosaavn.com/; This is especially confusing when the user searches for an artist whose songs are on Spotify, but not on JioSaavn.

**Describe the solution you'd like**
Explain to the user that this app uses JioSaavn as streaming backend.

**Comment by Sangwan5688** [comment]
Neither me nor the app claims that the music is coming from Spotify. It's clearly mentioned on all other issues too which are pinned that music is coming from JioSaavn in whole app (except youtube section, where it's from youtube). Anyway, I will put it clearly in Readme file or in FAQs where exactly music is coming from.
