### ISSUE TITLE
Move the "View All" button towards the top

### ISSUE THREAD

**Issue by CommanderEntropy** [Sangwan5688/BlackHole#204]
**Is your feature request related to a problem? Please describe.**
When searching in BlackHole, some results are hidden behind a "View All" button. It would be nice if the "View All" button was moved towards the top next to the section headers for quick access when we see that the song we want isn't in the first few results. Instead, we have to scroll down and look for the button. Most people are used to such buttons being on the top.

**Describe the solution you'd like**
The "View All" button is moved to the top. (Example screenshot provided)

**Additional context**
![BlackHole Suggestion](https://user-images.githubusercontent.com/83172580/147413371-dc1e27fe-c0c8-49ee-a0f4-c354a1a8bc72.jpg)

**Comment by Sangwan5688** [comment]
Cool, will do in next update
