### ISSUE TITLE
Add support for Macos

### ISSUE THREAD

**Issue by rupisaini123** [Sangwan5688/BlackHole#206]
Hi, 
I love your app. I works fine on ios but i can't build it for macos.
Can you please add support for macos too.

Thanks,

**Comment by Sangwan5688** [comment]
I don't have a macOS, so if you want to build it for macOS just add support for it. You can go through [the guide](https://docs.flutter.dev/desktop) on how to enable and compile it. If you face any issue just comment it here.

**Comment by rupisaini123** [comment]
I tried tried multiple times, but it keeps on giving me errors.
/Tools/Devloper/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_archive-4.1.0/macos/Classes/SwiftFlutterArchivePlugin.swift:1:1: error: expressions are not allowed at the top level
../../ios/Classes/SwiftFlutterArchivePlugin.swift
^
/Tools/Devloper/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_archive-4.1.0/macos/Classes/FlutterArchivePlugin.swift:6:5: error: cannot find 'SwiftFlutterArchivePlugin' in scope
    SwiftFlutterArchivePlugin.register(with: registrar);
    ^~~~~~~~~~~~~~~~~~~~~~~~~
/Tools/Devloper/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_archive-4.1.0/macos/Classes/SwiftFlutterArchivePlugin.swift:1:1: error: cannot find operator '../../' in scope
../../ios/Classes/SwiftFlutterArchivePlugin.swift
^~~~~~
/Tools/Devloper/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_archive-4.1.0/macos/Classes/SwiftFlutterArchivePlugin.swift:1:7: error: cannot find 'ios' in scope
../../ios/Classes/SwiftFlutterArchivePlugin.swift
      ^~~
/Tools/Devloper/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_archive-4.1.0/macos/Classes/SwiftFlutterArchivePlugin.swift:1:11: error: cannot find 'Classes' in scope
../../ios/Classes/SwiftFlutterArchivePlugin.swift
          ^~~~~~~
/Tools/Devloper/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_archive-4.1.0/macos/Classes/SwiftFlutterArchivePlugin.swift:1:19: error: cannot find 'SwiftFlutterArchivePlugin' in scope
../../ios/Classes/SwiftFlutterArchivePlugin.swift
                  ^~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Sangwan5688** [comment]
Hmm, looks like it's an issue with the package `flutter_archive`. I see that an [issue](https://github.com/kineapps/flutter_archive/issues/43) is already open for that. There's no update regarding the same but let's see what happens. Till then you can try building after removing the package. Just remove it from `pubspec.yaml` file and try again.

**Comment by topcheese** [comment]
So this should be fixed now by increasing flutter_archive 
 to ^4.1.1.

**Comment by Surendrajat** [comment]
<img width="1045" alt="Screenshot 2022-01-26 at 17 06 21" src="https://user-images.githubusercontent.com/11215000/151156979-025cb6ac-71cf-4691-b10d-819006a2ccc1.png">

---

Playback works fine for both JioSaavn & YT once you add [this key for network permission](https://github.com/flutter/flutter/issues/47606#issuecomment-568522318). Download doesn't work, tho. I'm on macOS 12(intel).

**Comment by Sangwan5688** [comment]
Closing this as macos is now supported along with Downloads
