### ISSUE TITLE
lyrics do not work with or without vpn

### ISSUE THREAD

**Issue by Relected** [Sangwan5688/BlackHole#207]
**Describe the bug**

so uhh, this happens a lot when i try to view lyrics or whenever i try to download songs with lyrics and the lyrics doesnt get downloaded when i download the song (i dont know if they should be added into the song itself or saved separately as a synced .lrc file)

**To Reproduce**
1. i open any song that has lyrics
2. Click on the music note an the top right
3. the error appears

**Expected behavior**

i should get the lyrics for the song or at least be able to download them

**Screenshots**

![Screenshot_20211228_233415_com shadow blackhole](https://user-images.githubusercontent.com/61807003/147652536-c76c2c60-deae-4cb0-a416-d3d6cf92ce55.jpg)

**Smartphone (please complete the following information):**
 - Device: [Huawei Y9 2018]
 - OS: [Android 9]
 - App Version [v1.13]

**App Logs**
If possible please provide app logs here.

i cant find logs

**Comment by Sangwan5688** [comment]
This error is most probably due to captcha or something. See BlackHole first tries to search lyrics on JioSaavn, if it's not available there it fetches them from MusixMatch and if it's not available on musixmatch too then it tries to scrape it from google. So it's definitely fetched from google as seen by all the text. Now that error can be coz of captcha or something which blocked the search and instead of scrapping lyrics it scraped something else.

**Comment by BrightDV** [comment]
I had a similar problem when BlackHole is trying to fetch lyrics from Musixmatch

![Screenshot_20220102-083842.png](https://user-images.githubusercontent.com/92821484/147869330-8bfceffc-8bd4-44ea-b60c-dfaf11fd2083.png)

**Comment by Relected** [comment]
@Sangwan5688 weird, some song that has lyrics on musixmatch didn't appear on blackhole, also why are the lyrics saved as Metadata and not .lrc files? I thought that lyrics from musixmatch are supposed to be synchronized, right?

**Comment by Sangwan5688** [comment]
@Relected MusixMatch doesn't provide those lrc files for free. There are some restrictions like just 500 requests/month or so which aren't enough for BlackHole. So it just scrapes lyrics from their website (just the text) and saves it in metadata

**Comment by Relected** [comment]
@Sangwan5688  well I have musixmatch premium in my phone, maybe you can use the musixmatch app as a plugin to synchronize lyrics and save them as lrc similar to how poweramp  does it?
