### ISSUE TITLE
It turns out to you not all the songs are being played for IOS devices?

### ISSUE THREAD

**Issue by ghost** [Sangwan5688/BlackHole#217]
**Describe the bug**

**To Reproduce**
3. Do this and that

**Expected behavior**

**Screenshots**

**Device Details (please complete the following information):**
 - OS: [e.g. Android, Windows, iOS, Linux]
 - Version: [e.g. Android 12, iOS 15, Windows 11 20H2]
 - Device: [e.g. Pixel 4, iPhone 13]
 - App Version [e.g. v1.13.0]

**App Logs**
If possible please provide app logs here.
[](url

https://user-images.githubusercontent.com/62659188/149926143-872e667c-cc69-49d3-9572-a722e57978ff.mov

)

**Comment by Sangwan5688** [comment]
Please provide more info, as you are already debugging, you can easily provide app logs. An issue with just the title and no info will be closed.

**Comment by Fernando321438** [comment]
He doesn't give me mistakes but I don't understand why many songs just don't start, I would like to understand why, thanks.

**Comment by Sangwan5688** [comment]
@Fernando321438 I told you I can't tell anything without logs. Neither I have iOS or something to test the app on it neither I'm familiar with this issue. So I can't tell anything. So, provide logs.

**Comment by Fernando321438** [comment]
These are the logs that come out to me when the music doesn't start.
<img width="449" alt="Schermata 2022-01-18 alle 17 49 19" src="https://user-images.githubusercontent.com/62659188/149981818-96e0f229-6c2c-4c85-8312-b6298cd03985.png">

**Comment by Sangwan5688** [comment]
Looks like it failed to connect to the host. Some network issue or maybe some website issue. Needs more investigation

**Comment by Sangwan5688** [comment]
fixed in latest version
