### ISSUE TITLE
Sometimes asks for connecting to indian vpn

### ISSUE THREAD

**Issue by ilyasbabu** [Sangwan5688/BlackHole#219]
**Describe the bug**
On Spotify list on global section, while choosing some songs it shows 'sorry results not found' and asks for connecting to indian vpn

**To Reproduce**
1. Go to 'spotify charts'
2. Click on 'click on global.'
3. And select 4th item (enemy by imagine dragons)
4. And the can be seen

**Expected behavior**
Expects to see that particular song and albums

**Screenshots**
![Screenshot_2022-01-19-22-50-05-718_com.shadow.blackhole.jpg](https://user-images.githubusercontent.com/86759152/150183205-9563a3a1-b046-48b6-b78e-80f78d636e9b.jpg)

**Device Details (please complete the following information):**
 - OS: android
 - Version: android 10
 - Device: Poco m2 pro gram
 - App Version - latest

**Comment by Sangwan5688** [comment]
Please refer to #52
