### ISSUE TITLE
like button in notification bar

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Sangwan5688/BlackHole#220]
**Is your feature request related to a problem? Please describe.**
It is not a good user experience that I want to open the app to add music to my liked songs playlist. It will be fine if we have a like button on notification bar, so we can like the currently playing song without opening the app.

**Describe the solution you'd like**
Add a like button in the app's notification bar along with the controllers of the current playing song.

**Describe alternatives you've considered**
All we have to do is let the users like the song they are currently playing, without opening the app. Any feature or solution this issue resolves will approve.

**Additional context**
Existing notification bar of the app:-
<img src="https://user-images.githubusercontent.com/73386156/150201793-cdab8dd6-7bc7-4875-8d60-e140ca3c4dd1.jpg" width="70%" />

Expecting something like this:-
<img src="https://user-images.githubusercontent.com/73386156/150203267-17253326-e5d6-4cd2-ac48-09a0e761241d.png" width="70%" />

**Comment by Sangwan5688** [comment]
There have been some requests regarding that but actually it's not possible for me to add that as of now. The notification is actually handled by a package `audio_service`. And it doesn't support an option to add custom buttons as of now. I will personally add the feature whenever I'm able to do so, but it's not possible as of now. I will keep the issue open and lets see when we can work on that in future

**Comment by Sangwan5688** [comment]
This is already done, closing issue
