### ISSUE TITLE
Youtube downloads not playing

### ISSUE THREAD

**Issue by lessgoo00** [Sangwan5688/BlackHole#223]
Songs downloaded from Youtube aren't playing and they're file size is 0b

**Comment by Sangwan5688** [comment]
If it's size is 0b then it just means it never got downloaded. It might be coz you closed the application or something. Afaik there's no issue with the download not working.

**Comment by lessgoo00** [comment]
I didn’t close the app or anything, I stayed on the player screen

**Comment by topcheese** [comment]
The last release still seems good. Is this a desktop build?

**Comment by lessgoo00** [comment]
There are desktop builds? Also, no i'm not using a desktop build

**Comment by topcheese** [comment]
@lessgoo00 I'm not aware of any official builds, but I do see desktop folders, so it's possible to try and build.

**Comment by BrightDV** [comment]
The desktop builds are on BlackHole's Telegram channel. You can find the channel's link in the readme file.

**Comment by Sangwan5688** [comment]
Ok, the issue was caused because of quality changes during download. The app was modifying url as per quality selected in settings. But, it was supposed to modify only urls from home section not from youtube. I will fix it in next commit

**Comment by lessgoo00** [comment]
Thanks
