### ISSUE TITLE
The Speed Thing is kinda glitchy

### ISSUE THREAD

**Issue by Raif1** [Sangwan5688/BlackHole#228]
**Is your feature request related to a problem? Please describe.*ye*
A clear and concise description of what the problem is. Ex. I'm always frustrated when [.The speed changer is too close to the track slider..]

**Describe the solution you'd like*position of the speed changer should be repositioned to the hamburger menu or somewhere better
![croppedImage](https://user-images.githubusercontent.com/93464125/150956500-badfef73-cdfa-4d0f-9759-1476f69c7744.png)
 *

**Describe alternatives you've considered**

**Additional context**

**Comment by Sangwan5688** [comment]
Cool, will fix it soon

**Comment by Raif1** [comment]
So i have another issue so should i
 mention it here or file another issue (kinda new to github)

**Comment by Sangwan5688** [comment]
fixed in latest version

**Comment by Raif1** [comment]
Thanks!
