### ISSUE TITLE
Spotify playlist download 

### ISSUE THREAD

**Issue by Raif1** [Sangwan5688/BlackHole#230]
**Is your feature request related to a problem? Please describe.*no*

**Describe the solution you'd like*Add an option to download spotify playlist and music through spotify link *

Its hard to download music one by one using search 

**Describe alternatives you've considered**

Add an option to download spotify playlist and music through spotify link 
**Additional context**

**Comment by kronos-2508** [comment]
It's already possible to import Spotify playlist through links. Head over to Library (bottom right) —> Playlists —> Import from Spotify. Then, you can download that playlist.

P.S. - BalckHole uses JioSaavn as a backend, not Spotify. So, it's possible that some songs aren't imported correctly or are missing. It just means that those particular songs aren't available on JioSaavn. You can use the YouTube section inside the app to download them.

**Comment by Raif1** [comment]
Ok thanks
