### ISSUE TITLE
Music stops when tab closed 

### ISSUE THREAD

**Issue by Raif1** [Sangwan5688/BlackHole#231]
**Problem**

When i close the blackhole tab music stops. This usually doesnt happen to music players. Sometimes i close all tabs which means the music stops too .

**Solution**

Make that the app works in the background .

**Comment by Sangwan5688** [comment]
The app works in background. I hope you understand what 'background' means.

**Comment by BrightDV** [comment]
Btw you can check in your settings if Stop music on App Close is checked or not if you want the music to be played when you close the app tab.
