### ISSUE TITLE
Use spotiflyer for downloading music

### ISSUE THREAD

**Issue by Raif1** [Sangwan5688/BlackHole#232]
**Describe the solution you'd like**
Add an option to Use spotiflyer to download music playlist albums etc. Bcs this will increase the apps functionality and the ability to download lot more music without any hassle.Coz it supports  lots of platforms.

**Additional context**
Link 
https://github.com/Shabinder/SpotiFlyer

**Comment by Sangwan5688** [comment]
Please don't add absurd requests.
