### ISSUE TITLE
I am from Philippines Can't Play Spotify Chart.

### ISSUE THREAD

**Issue by Bungeexgum** [Sangwan5688/BlackHole#240]
Hi, I'm new to this app anyway the issue is I can't play any Spotify song, idk if it's either my net connection or the app is not available in my country (Philippines) Then i realised i have to use VPN🤦🏼‍♂️ but then When i choose a certain song in Spotify Chart it wouldn't playing but instead searching then many similar title show up. Including indian songs😅 I am hoping for the future update where we don't have to use vpn.

**Comment by Sangwan5688** [comment]
Well, the app uses JioSaavn as the backend. And it's an issue with JioSaavn. It shows indian songs when users ip isn't indian. I can't actually do anything about that. Only jiosaavn can fix it.

**Comment by Bungeexgum** [comment]
> Well, the app uses JioSaavn as the backend. And it's an issue with JioSaavn. It shows indian songs when users ip isn't indian. I can't actually do anything about that. Only jiosaavn can fix it. I can't even provide any cookie or anything as it uses your ip address to get your location. And the only way to change ip address is to use a vpn or some kind of proxy (it needs to be indian server)

Well, i did try use a vpn but it still showed me Some Indian Songs, anyway is there no other way to be able to play Philippines song without using VPN. I tried searching indian proxy port in Google then copied, change my proxy and port in the app. I was thinking that it will work lol.

**Comment by Sangwan5688** [comment]
Well you can use the youtube section instead of home section. That way you will be able to play songs without vpn. But I would be honest youtube section isn't that much good as main section. But still it's worth it

**Comment by Bungeexgum** [comment]
> Well you can use the youtube section instead of home section. That way you will be able to play songs without vpn. But I would be honest youtube section isn't that much good as main section. But still it's worth it

Basically this app is only for indians.
