### ISSUE TITLE
Song resumes from start when you close and reopen the application

### ISSUE THREAD

**Issue by arun-421** [Sangwan5688/BlackHole#243]
**Describe the bug**
When you close the application while playing the song and reopen the application, the song plays from beginning instead of playing from the place it stops.

**To Reproduce**
1. Go to Blackhole 
2. Play a song
3. Close the application and clear application from background.
4. Now open the application
5. The song in the queue plays from the beginning

**Expected behavior**
When you re-open the application and play the song, the song should start from the point where it stopped. 

**Screenshots**
NA

**Device Details (please complete the following information):**
 - OS: [Android]
 - Version: [Android 10]
 - Device: [Redmi 7]
 - App Version [v1.13.0]

**App Logs**
NA

**Comment by Sangwan5688** [comment]
I think you mean the last played song. I think you mean that when last session loads, it loads the last played song but it plays from start not from where you stopped. Well, it's not actually a bug. Anyway, I will think about adding something for that too.

**Comment by arun-421** [comment]
Yes. It loads the last played song but it plays from start not from where I stopped. I hope if the last played song duration is saved in some file, or cache we can recover it and play it from where it stopped.

**Comment by Sangwan5688** [comment]
Ya, it can be done. Will try adding an option for that
