### ISSUE TITLE
Search provides the desired songs only if the correct spelling is given.

### ISSUE THREAD

**Issue by edjo241** [Sangwan5688/BlackHole#247]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when the search feature don't provide the desired song even if there is  one spell mistake.

**Describe the solution you'd like**
The search feature should provide the songs even if there is a minor spelling mistake. The searching technique should be improved.

**Describe alternatives you've considered**

**Additional context**

**Comment by Sangwan5688** [comment]
BlackHole don't handle all that. Whatever you type is directly sent to jiosaavn or youtube depending upon which section you are using. So, if the search isn't working with minor spelling mistakes then it's an issue with respective platforms, not with BlackHole, BlackHole is just a medium to send those requests.
