### ISSUE TITLE
A separate folder for songs downloaded using the app in my music .

### ISSUE THREAD

**Issue by NeutralDevop** [Sangwan5688/BlackHole#25]
A separate folder for the songs downloaded using the app would be nice because this will gather quality audios which were downloaded using the app for the user without searching for it.

**Comment by Sangwan5688** [comment]
Do you mean a separate folder on your device where songs are downloaded? or a separate option inside the app?

**Comment by Sangwan5688** [comment]
I have added the option. Although, songs downloaded before this commit won't be shown there. You can either download them again or if you have any `Audio Tag Editor` then just add `BlackHole` in the `comment` field.
