### ISSUE TITLE
The 'Already Exists' dialogue appear when u cancel a download and click on download again.
Also please fix the uppercase in the dialogue box in the 'Yes, but Replace Old' by replacing it with 'Yes, but replace old'

### ISSUE THREAD

**Issue by GoluLiliput** [Sangwan5688/BlackHole#252]
![IMG_20220209_170122.jpg](https://user-images.githubusercontent.com/60719832/153191911-a688df62-5fbd-4344-aef7-58e87f6530a0.jpg)

**Comment by GoluLiliput** [comment]
This thing is also present all over the settings page. There are many unnecessary uppercases. Not only this makes the app look slightly unprofessional, but also this would propagate when the app is translated to other languages.

**Comment by GoluLiliput** [comment]
If there is a way to help u edit all the uppercases and grammatical errors and stuffs all around the app, then I would love to help u in any way possible.

**Comment by Sangwan5688** [comment]
https://hosted.weblate.org/projects/blackhole/translations/
