### ISSUE TITLE
Lyrics Reading 

### ISSUE THREAD

**Issue by Raif1** [Sangwan5688/BlackHole#258]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I want to see the app highlighting the lyrics when its being said 

**Describe alternatives you've considered**

Spotify works nice 

Image 

![Capture.JPG](https://user-images.githubusercontent.com/93464125/155885892-4ca70622-65a9-479e-8c26-1783bf7704af.JPG)

Tho its a desktop imahe you get the idea

**Additional context**

**Comment by BrightDV** [comment]
Check [this comment](https://github.com/Sangwan5688/BlackHole/issues/207#issuecomment-1003692554) as an answer.
Spotify pay to fetch synced lyrics from MusixMatch.

**Comment by Raif1** [comment]
Well  then

**Comment by BrightDV** [comment]
However, another FOSS android player, [APlayer](https://github.com/rRemix/APlayer) has support of synced lyrics.
I have searched in the code, and the sites used to get the synced lyrics are [here](https://github.com/rRemix/APlayer/blob/3ab6d60e74da16c928675367a7a46be2c72496b6/app/src/main/java/remix/myplayer/request/network/HttpClient.kt#L146).
Also, I have tried the app and the synced lyrics can work without any VPN.
However, I don't know how secure these sites are nor the way to get the lyrics.
I will do some workaround around this and update my comment. Maybe the issue can be reopened
