### ISSUE TITLE
Video as mp3

### ISSUE THREAD

**Issue by brnwlshubh** [Sangwan5688/BlackHole#27]
**Is your feature request related to a problem? Please describe.**
As I want to play video as mp3 sometimes by not watching video.

**Describe the solution you'd like**
Please add option to view and play the video file as music.

**Describe alternatives you've considered**
This feature is available in Musicolet app.

**Comment by Sangwan5688** [comment]
It can be implemented, just have to make some changes in UI. What kind of video formats do you want to be supported?

**Comment by brnwlshubh** [comment]
M4A,WEBM,MP4,MKV,MKV

**Comment by brnwlshubh** [comment]
Please try to implement this feature in your upcoming release.

**Comment by Sangwan5688** [comment]
I have added a "videos" tab with all these video formats. As requested the videos will play just like audio but there's won't be an image or anything. Also, the name of the video will be the one with which it is saved on the device, not the one embedded in the metadata. You will be able to see changes in the new upcoming update (will be released next week).

**Comment by brnwlshubh** [comment]
> It can be implemented, just have to make some changes in UI. What kind of video formats do you want to be supported?

Please add ".opus" also

**Comment by Sangwan5688** [comment]
I don't think I will be able to support that. Will have to look into it.
Then I will let you know.

sangwan
