### ISSUE TITLE
API does not work

### ISSUE THREAD

**Issue by muhammadkamel** [Sangwan5688/BlackHole#273]
API >> https://www.jiosaavn.com/api.php?_format=json&_marker=0&api_version=4&ctx=web6dot0

Doesn't work and response is
![Screen Shot 2022-03-26 at 10 23 28 AM](https://user-images.githubusercontent.com/17657941/160231309-a0141c35-5837-4cc6-8676-e20fc8bd54cb.png)

**Comment by Sangwan5688** [comment]
BlackHole doesn't own and has nothing to do with any of the APIs used inside the app.

**Comment by muhammadkamel** [comment]
What does it mean?

**Comment by BrightDV** [comment]
BlackHole is only a front-end for JioSaavn & YouTube. It only scrapes the data from this sites and APIs.
