### ISSUE TITLE
Synced Lyrics

### ISSUE THREAD

**Issue by BrightDV** [Sangwan5688/BlackHole#274]
**Is your feature request related to a problem? Please describe.**
Adding synced lyrics to the app would be very nice! 
Also, #258 has been closed.

**Describe the solution you'd like**
In the lyrics screen, using a ListView which autoscrolls to the good sentence. [Harmonoid managed to do it here (in Dart).](https://github.com/harmonoid/harmonoid/blob/3e68b765616d5017373edc11b4907558a647261b/lib/interface/now_playing.dart#L295)

**Describe alternatives you've considered**
/

**Additional context**
I have done some research about this and found a FOSS Player, [APlayer](https://github.com/rRemix/APlayer) which has support of synced lyrics. I have searched in the code, and the sites used to get the synced lyrics are [here](https://github.com/rRemix/APlayer/blob/3ab6d60e74da16c928675367a7a46be2c72496b6/app/src/main/java/remix/myplayer/request/network/HttpClient.kt#L146).
Also, I have tried the app and the synced lyrics can work without any VPN. However, I don't know how secure these sites are.
I did some workaround around this. Here are the two main services used:

<table>
<tr>
	<td>Service
	<td>Base URL
	<td>Example URL to search a song to get lyrics ID
	<td>Example URL to get lyrics with its ID got before
	<td>Notes
<tr>
	<td>Kugou
	<td>http://lyrics.kugou.com
	<td>/search?ver=1&man=yes&client=pc&keyword=Alan%20Walker-Alone&duration=160450&hash=
	<td>/download?ver=1&client=pc&fmt=lrc&charset=utf8&id=28031851&accesskey=2999D9497C5735B1A7F5B522E1EB5AF7
	<td>Needs an access key
<tr>
	<td>Netease
	<td>http://music.163.com/api
	<td>/search/get?s=Alan%20Walker-Alone&offset=0&limit=1&type=1
	<td>/song/lyric?os=pc&id=444269135&lv=-1&kv=-1&tv=-1
	<td>Don't need an access key
</table>

Using [lyrics_parser](https://pub.dev/packages/lyrics_parser) should help to decode the lyrics data.

## EDIT
I found a Flutter Music Player ([SpoTube](https://github.com/KRTirtho/spotube)) that supports synced lyrics too. He gets the lyrics from [another website](https://github.com/KRTirtho/spotube/blob/83a45dd9b6244b81088a7ac8ddf2903f3774284d/lib/helpers/timed-lyrics.dart#L37) which isn't Chinese.

**Comment by Sangwan5688** [comment]
Cool, I will have a look over them and will try to add it soon.
