### ISSUE TITLE
Error Type 'One byte string'

### ISSUE THREAD

**Issue by saurabhinabys** [Sangwan5688/BlackHole#282]
Steps to Reproduce:
1.Searched for Radiohead
2. Clicked on Saavn made playlist
![Screenshot_20220407-125041](https://user-images.githubusercontent.com/46681584/162143175-ec9463f4-5da4-4b52-860e-8964f0e28b44.png)

**Comment by BrightDV** [comment]
Are you using a VPN with an Indian server? If not, consider using one as JioSaavn blocks request for non-Indian songs if your IP don't come from India.

**Comment by saurabhinabys** [comment]
> Are you using a VPN with an Indian server? If not, consider using one as JioSaavn blocks request for non-Indian songs if your IP don't come from India.

No, my IP is indian and everything else just works fine.

**Comment by BrightDV** [comment]
I have done more research and it seems like the playlist [has no songs on the website itself.](https://www.jiosaavn.com/featured/radiohead/c3LMRRin9vXfemJ68FuXsA__)
Maybe BlackHole should handle these playlists better.

**Comment by tootbrute** [comment]
Sorry, I filed the same bug https://github.com/Sangwan5688/BlackHole/issues/305

Yes it should handle it better. Maybe don't even show the playlist. Basically every playlist gives me this error. Is it usable for others outside of India?

**Comment by Sangwan5688** [comment]
I can't be sure if it's really due to an empty playlist. Coz in that case, it shouldn't happen with playlists that contain songs (in the case of #305). There can be any other issue. I will try reproducing it.

**Comment by Sangwan5688** [comment]
Lemme know if it's fixed in the next beta or not. Feel free to reopen the issue if it's not fixed

**Comment by tootbrute** [comment]
> Lemme know if it's fixed in the next beta or not. Feel free to reopen the issue if it's not fixed

Still not working for me.
