### ISSUE TITLE
Add Pakistan to list of local charts

### ISSUE THREAD

**Issue by aadilayub** [Sangwan5688/BlackHole#283]
Thanks so much for making this app. It's a great complemwnt for people who use local-only/self-hosted music libraries and don't use Spotify out of principle. 🙏

It would be great if you could also add Pakistan to the list of local charts.

**Comment by Sangwan5688** [comment]
All local charts are directly scraped from Spotify. I can't add your country myself. If it is on Spotify, I will be happy to add it. Otherwise I can't do anything.

**Comment by aadilayub** [comment]
Ah I see. Spotify is definitely available in Pakistan, but it seems local charts haven't rolled out here yet

https://community.spotify.com/t5/Live-Ideas/Community-Connect-Spotify-Charts-in-Pakistan/idi-p/5212825#comments
