### ISSUE TITLE
Visual Bug in Android Mobile App (Overflow error in Playlist Page)

### ISSUE THREAD

**Issue by badushaebrahim** [Sangwan5688/BlackHole#284]
**Describe the bug**
there is An overFlow error in Playlist Download when we already Have Song Download the ReDownload Popup Comes With Over Flow Error

**To Reproduce**
1. Open App
2. Go To Any Play List 
3. Press Download Button For Any one Song
4. press Download Button For All Song Then The ReDownload Pop UP Come At Android it has Over Flow error

**Expected behavior**
No Pop UP Error

**Screenshots**
![0fe59c54-f6d7-4a3f-a9c2-5d7f022ab10f](https://user-images.githubusercontent.com/63869474/162760987-f2c9d0e3-bb69-4912-803b-016ddc87509e.jpg)

**Device Details (please complete the following information):**
 - OS:  Android
 - Version: 9
 - Device: Vivo U20
 - App Version Latest

**App Logs**
If possible please provide app logs here.

#i Found Fix So Then What Is to Do for Adding it for Pull request 
ps:I AM new Here

**Comment by badushaebrahim** [comment]
i Have Fixed this in My Local Copy an would Like to Add it To whole version

**Comment by Sangwan5688** [comment]
Closed with #285
