### ISSUE TITLE
Spotify Top 200 Error

### ISSUE THREAD

**Issue by Sangwan5688** [Sangwan5688/BlackHole#3]
To prevent the Spotify Charts Page from DDoS, some changes have been made to the website resulting in Top 200 Songs not loading.

**Comment by Sangwan5688** [comment]
As of now, I couldn't find any workaround reading the issue. So, I am thinking to fetch top charts from somewhere else.
Any suggestions regarding API, charts, website or anything else that I can use to show top charts are welcomed and will be implemented in the app if found good enough.

**Comment by ntbk1919** [comment]
Dunno about Api but what about
https://spotifycharts.com/regional/

**Comment by Sarlay** [comment]
Maybe you can try Deezer API.
I don't really understand if that's what you are looking for but may be an alternative.
