### ISSUE TITLE
[Windows] Add Blackhole to Chocolatey community repo

### ISSUE THREAD

**Issue by vairag22** [Sangwan5688/BlackHole#307]
Add Blackhole for Windows to [Chocolatey Community Package Repository](https://community.chocolatey.org/packages).
(Chocolatey is package manager for Windows like APT or Pacman for Linux)

**Comment by dmdhrumilmistry** [comment]
@vairag22 Chocolatey seems to be a good package installer for windows, but Microsoft has their own package installer. Winget packages information can be found on their official [repo](https://github.com/microsoft/winget-pkgs).

**Comment by vairag22** [comment]
I am aware of WinGet but Chocolatey is much better. It has more packages, significantly wider userbase and more options for package management. As of writing this VSCode is 4 months out of date on Microsoft's own package manager WinGet.

**Comment by vairag22** [comment]
Closing this issue, more than a year has passed without any updates from devs' side.

**Comment by Sangwan5688** [comment]
@vairag22 Windows version is not even maintained anymore and has many bugs. It's not a good time to add it there yet.
