### ISSUE TITLE
iOS Youtube playback issue

### ISSUE THREAD

**Issue by radughitescu** [Sangwan5688/BlackHole#320]
Hi, i've noticed that only on iOS, in the youtube section sometimes the playback isn't working.
Steps to reproduce:
1.Get latest version of blackhole
2.Run blackhole iOS app
3.Go to youtube section
4.Search for a song
5.Play each song in the results
6.Sometimes a song opens but doesn't play, it's stuck at 0:00 with no obvious error message

Has anyone encountered this ?

**Comment by radughitescu** [comment]
I've found the issue.
The problem occurs when the mime type in the url is webm, apparently audio_service or just_audio miss a codec on ios side or something of this sort.
Any ideas on how to get only mp4 urls from youtube?

**Comment by Sangwan5688** [comment]
You can filter out the urls. Each youtube video data contains a `container` type and `codec` type info. You can use them to check if it's m4a or webm.

**Comment by radughitescu** [comment]
Sorry I did not express myself correctly, i've figured out a way to filter out webm urls but i'm wondering if there's a way to get an mp4 alternative url from a webm url. Thanks for the reply!

**Comment by Sangwan5688** [comment]
Every video has both m4a and webm URLs, and they are all available when you access the audio stream of those videos. I guess blackhole takes the top and lowest quality URLs from them. As for m4a and webm I think it prefers m4a, and if m4a isn't available, then it takes webm URLs. Or maybe it just checks bitrate; not sure I forgot; I will have to check the code.

**Comment by radughitescu** [comment]
Oooooh, great!!! Thanks!
I'll look it up, if i manage to fix it i can do a pull request so that everyone will have the fix.

**Comment by Sangwan5688** [comment]
Sure, the code will most probably in youtube_services.dart file. You can look it up in that where it extracts those audio links.

**Comment by tecrodrigocastro** [comment]
@radughitescu did you find a solution for this bug?

**Comment by radughitescu** [comment]
> 

yeah i did, i'll look it up and post it when i have the time

**Comment by tecrodrigocastro** [comment]
> > 
> 
> yeah i did, i'll look it up and post it when i have the time

please, thank you so much

**Comment by tecrodrigocastro** [comment]
@radughitescu Any returns? I still haven't been able to resolve this bug.

**Comment by radughitescu** [comment]
try to replace `formatVideo()` in youtube_services.dart with this
`  Future<Map?> formatVideo({
    required Video video,
    required String quality,
    // bool preferM4a = true,
  }) async {
    if (video.duration?.inSeconds == null) return null;
    final List urls = await getUri(video);
    String urlMp4 = '';
    bool found = false;
    urls.forEach((element) {
      if (element.toString().contains('mp4')) {
        urlMp4 = element.toString();
        found = true;
      }
    });
    if (urlMp4.isEmpty) {
      urlMp4 = urls.first.toString();
    }
    print('URLS: $found');
    return {
      'id': video.id.value,
      'album': video.author,
      'duration': video.duration?.inSeconds.toString(),
      'title': video.title,
      'artist': video.author,
      'image': video.thumbnails.maxResUrl,
      'secondImage': video.thumbnails.highResUrl,
      'language': 'YouTube',
      'genre': 'YouTube',
      'url': urlMp4,
      'lowUrl': urlMp4,
      'highUrl': urlMp4,
      'year': video.uploadDate?.year.toString(),
      '320kbps': 'false',
      'has_lyrics': 'false',
      'release_date': video.publishDate.toString(),
      'album_id': video.channelId.value,
      'subtitle': video.author,
      'perma_url': video.url,
    };
  }`

I've modified the method to search only for mp4 urls and add them in the return object.
It's been a while since i've worked on this and i'm backed up with work now, it will be a few days until i can provide a full answer

**Comment by Sangwan5688** [comment]
fixed with latest commit
