### ISSUE TITLE
Can't search and play songs through saavn


### ISSUE THREAD

**Issue by AshPulkit29** [Sangwan5688/BlackHole#329]
![Screenshot_20220603-182844.jpg](https://user-images.githubusercontent.com/104251115/171858597-f9460db0-46ac-496d-8c15-a3d04d31a246.jpg)

**Comment by Sangwan5688** [comment]
Saavn servers are down since morning. It's not a BlackHole side issue. I hope it will be fixed soon from their side.

**Comment by AshPulkit29** [comment]
> Saavn servers are down since morning. It's not a BlackHole side issue. I hope it will be fixed soon from their side.

Ok👍. Thanks for replying
