### ISSUE TITLE
Interface display problems

### ISSUE THREAD

**Issue by guolidaxian** [Sangwan5688/BlackHole#33]
1, when the music playing, minimize the play after the panel, then open the panel, display problems
2, when the network is slow, has not been finished loading, then click on the panel, display also can appear problem
 
![QQ图片20210601085050](https://user-images.githubusercontent.com/79434985/120252245-89ffa100-c2b6-11eb-9456-25c9903757b1.jpg)
![QQ图片20210601085029](https://user-images.githubusercontent.com/79434985/120252254-8f5ceb80-c2b6-11eb-978b-0e3a1f48ae79.jpg)

**Comment by Sangwan5688** [comment]
I already know about the first problem it's because of the `SafeArea`. The mini player is trying to expand to the whole screen whereas the home screen is in Safe Area. I tried fixing it but still not successful. Although it doesn't appear in the release version so I left it as it is. Now coming over to the second problem. Can you please explain it more in detail. Please provide the details asked for in the bug issue format.

**Comment by ogbodotg** [comment]
Yes. The second error appears when you double tap the miniplayer on the home.
It produces the error => type 'String' is not a subtype of type 'bool'
The relevant error-causing widget was => PlayScreen

Also, a similar error happens whenever I try to play 'Last Session' songs.
Error is => type 'String' is not a subtype of type 'int' of 'index'
The relevant error-causing widget was => PlayScreen

**Comment by Sangwan5688** [comment]
@ogbodotg I'm not able to reproduce the error on double-tap. Can you provide more details and even app logs, if possible.

**Comment by guolidaxian** [comment]
> I already know about the first problem it's because of the `SafeArea`. The mini player is trying to expand to the whole screen whereas the home screen is in Safe Area. I tried fixing it but still not successful. Although it doesn't appear in the release version so I left it as it is. Now coming over to the second problem. Can you please explain it more in detail. Please provide the details asked for in the bug issue format.

Probably is, when the network is slow, pictures haven't load out, click on the panel, or sliding, problems will occur

**Comment by ogbodotg** [comment]
> @ogbodotg I'm not able to reproduce the error on double-tap. Can you provide more details and even app logs, if possible.

This first error appears when you try to open the miniplayer while song is playing.
![image](https://user-images.githubusercontent.com/63649963/120430377-d4dcef80-c36e-11eb-86a6-a76203272f85.png)

The second error appears across many pages/widgets; Last Session, downloads, favourites, playlists.
![image](https://user-images.githubusercontent.com/63649963/120430591-25544d00-c36f-11eb-84a1-757a65c75b66.png)

Will these help?

**Comment by Sangwan5688** [comment]
I think it is because of the changes I made to API a few days ago. Can you try it using the latest commit and with app data cleared.

**Comment by ogbodotg** [comment]
@Sangwan5688  I have done that. Cleared app data, uninstalled and reinstalled app with latest commit, but errors still persist. I am not sure what the problem is. 

Could it be because i am also fetching song files from a different source?

**Comment by Sangwan5688** [comment]
@ogbodotg Yes, that is most probably the reason. As the playlists, favorites, etc. everything related to online has its own metadata. If you use any other source then the format of API response will be different which will cause issues in the app. If you want to change the source then make changes in code too.
