### ISSUE TITLE
Android apk vpn errro from india

### ISSUE THREAD

**Issue by rohitrmakwana** [Sangwan5688/BlackHole#334]
Latest versions v1.14.0 got error so unable to play any songs from any album what is the resolution?

**Comment by Lokawn** [comment]
I am getting the same error.

**Comment by badushaebrahim** [comment]
i am get error while trying to connect to server of playlist info

**Comment by Sangwan5688** [comment]
Duplicate of #329

**Comment by Sangwan5688** [comment]
Servers are up again you can continue playing
