### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by DesirArman007** [Sangwan5688/BlackHole#340]
Spotify tab showing error: Service unavailable?

Idk if it existed before or not i downloaded it today.

![Screenshot_2022-06-10-18-05-18-58_a2df05e64545de9e48d383611b669e6e](https://user-images.githubusercontent.com/94918174/173065422-7018866d-c799-4894-a7e8-514fa6921de3.jpg)

![Screenshot_2022-06-10-18-05-21-50_a2df05e64545de9e48d383611b669e6e](https://user-images.githubusercontent.com/94918174/173065407-67885025-1f01-47ff-a204-6630065456f9.jpg)

**Comment by Sangwan5688** [comment]
BlackHole used to parse Spotify charts website. But recently they changed the whole website coz of which blackhole is no longer able to parse the website and that's why you encounter this issue. It will be fixed in next version.

**Comment by DesirArman007** [comment]
> BlackHole used to parse Spotify charts website. But recently they changed the whole website coz of which blackhole is no longer able to parse the website and that's why you encounter this issue. It will be fixed in next version.

One more thing when I play the download songs after it finished playing them it stuck on the last song in the download section eventho a different song is playing.

**Comment by Sangwan5688** [comment]
> > BlackHole used to parse Spotify charts website. But recently they changed the whole website coz of which blackhole is no longer able to parse the website and that's why you encounter this issue. It will be fixed in next version.
> 
> One more thing when I play the download songs after it finished playing them it stuck on the last song in the download section eventho a different song is playing.

I will have to check.

**Comment by DesirArman007** [comment]
[

https://user-images.githubusercontent.com/94918174/173214072-68867160-3954-4273-8c30-32b62949b579.mp4

](url)

**Comment by DesirArman007** [comment]
> > > BlackHole used to parse Spotify charts website. But recently they changed the whole website coz of which blackhole is no longer able to parse the website and that's why you encounter this issue. It will be fixed in next version.
> > 
> > 
> > One more thing when I play the download songs after it finished playing them it stuck on the last song in the download section eventho a different song is playing.
> 
> I will have to check.

Here I've recorded it


https://user-images.githubusercontent.com/94918174/173214283-a1bdade1-ce2e-45a4-9795-49f319f3954a.mp4

**Comment by Sangwan5688** [comment]
Have been fixed
