### ISSUE TITLE
Stable Proxy support

### ISSUE THREAD

**Issue by knightmob** [Sangwan5688/BlackHole#342]
Hi! I'm from the Philippines, now I'm wondering how can I make blackhole work in my country? The default proxy IP and port is not working, can you pls recommend a working proxy and port that works in the Philippines?

**Comment by BrightDV** [comment]
At the moment, the in-app proxy doesn't work very well. You can try using an indian VPN instead.

**Comment by knightmob** [comment]
> At the moment, the in-app proxy doesn't work very well. You can try using an indian VPN instead.

Sad but thanks, I wonder if you will fix this issue or at least find another suitable Indian proxy recommendation! But hey thanks for the help!

**Comment by yarons** [comment]
@knightmob Hey, can you please edit the title to make it more meaningful? Maybe "Internal proxy support" or something like that?

BTW you can try [Orbot](https://guardianproject.info/apps/org.torproject.android/).

**Comment by Sangwan5688** [comment]
Closing this as inapp Proxy is relatively stable now.
