### ISSUE TITLE
Youtube as a library

### ISSUE THREAD

**Issue by asifmhdashik** [Sangwan5688/BlackHole#35]
I would like to have YouTube as a library for downloading and playing songs. Which would broaden the search accuracy and availability of wide variety songs and  podcasts too.

**Comment by Sangwan5688** [comment]
It will take time but I will try to add it. But as told earlier I won't make it the default.

**Comment by iripu** [comment]
> It will take time but I will try to add it. But as told earlier I won't make it the default.

That's great. People who want yt can switch to yt mode as an alternative for gogle's ytube music player.
