### ISSUE TITLE
licenses inconsistency

### ISSUE THREAD

**Issue by SoftwareEthicsResearcher** [Sangwan5688/BlackHole#350]
Hello, I am doing research in software engineering ethics. I found different licenses in repo. May I know which license repo follows? I would like to highlight this as a transparency concern.
•  Repo License: GNU General Public License v3.0, 
o  Different license : MIT in docs/scripts/bootstrap-datepicker.js.
 
Regards, Software Ethics Researcher.

**Comment by Sangwan5688** [comment]
The app uses GNU General Public License v3.0.
I'm not sure why MIT license is there, most probably it's related to the BlackHole website. as the website is also in this repo itself
