### ISSUE TITLE
India server of Spotify is not connecting 

### ISSUE THREAD

**Issue by abhishekm5577** [Sangwan5688/BlackHole#354]
After many attempts still the spotify server is unavailable for any country server and many are finding this issue and it is not dependant of network speed. ![Screen!shot_2022-06-27-16-07-24-849_com shadow blackhole](https://user-images.githubusercontent.com/76815473/175923166-38af28ec-f27b-4468-b997-5be2d1b6ee91.jpg)

**Comment by Sangwan5688** [comment]
duplicae of #360
