### ISSUE TITLE
Add an Useragent in the Web Viewer you have used.

### ISSUE THREAD

**Issue by ghost** [Sangwan5688/BlackHole#363]
Hello, Bro Add an Useragent in the webviewer you have used in this app. Because without any useragent we can't connect spotify account created using Google Signin. Google signin only loads in a verified Useragent.

Put this Useragent: Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.71 Mobile Safari/537.36

I really liked your Project. I will donate a small amount 100₹. I really like this. Design is so slick & classic and Cool. Try to use some animated and 3D Icons ( If Possible ). And also Need such Animations in App Gestures and Some Shortcut swipes to Change Song, Turn off the Player etc etc. But I really appreciate your work. Keep it up.

This Needs a Lots of Minor Modifications. I have found them. If you wish then I will tell.

**Comment by ariyandnath** [comment]
One More Thing, Please Work on this...

Please Move the Songs Arrangement on the Top after a Search. It wil help us to Play the song not to click on the album then play the song. I hope you understand.

**Comment by Sangwan5688** [comment]
App no longer use a webview, so it's not needed anymore
