### ISSUE TITLE
Cannot import Spotify playlist 

### ISSUE THREAD

**Issue by akkisavi** [Sangwan5688/BlackHole#367]
![Screenshot_2022-07-13-18-16-42-65_a2df05e64545de9e48d383611b669e6e](https://user-images.githubusercontent.com/109222838/178738409-2484a4ba-84d2-4bdc-b0b0-56748890487c.jpg)

**Comment by Sangwan5688** [comment]
fixed in latest commit [dd51af9](https://github.com/Sangwan5688/BlackHole/commit/dd51af900bdd0ff23f8f9ce79c6a7f291c68f768)
