### ISSUE TITLE
It's taking a long time to download a single song
Even if I just checked another app ehile downloading the music the downloading gets cancelled or is downloaded incompletly.
Please fix this..🥺

### ISSUE THREAD

**Issue by Coop04** [Sangwan5688/BlackHole#368]
**Describe the bug**

**To Reproduce**
3. Do this and that

**Expected behavior**

**Screenshots**

**Device Details (please complete the following information):**
 - OS: [e.g. Android, Windows, iOS, Linux]
 - Version: [e.g. Android 12, iOS 15, Windows 11 20H2]
 - Device: [e.g. Pixel 4, iPhone 13]
 - App Version [e.g. v1.13.0]

**App Logs**
If possible please provide app logs here.

**Comment by BrightDV** [comment]
Can you please fill the issue template?
Also, for the moment, there is no download manager so if you switch to another app, the download will stop, see #265.

**Comment by Sangwan5688** [comment]
Closed with 0877e8391bc6be8aeded1b41ceb7854125a61c80
