### ISSUE TITLE
Desktop Application for BlackHole

### ISSUE THREAD

**Issue by naqushab** [Sangwan5688/BlackHole#38]
As this is on Flutter, if it is possible to get a Desktop Application made out of it?

Thank you for the great application. Appreciate your efforts.

**Comment by Sangwan5688** [comment]
It definitely is possible, but some packages that the app uses are available only on Android. Still, there might be some workarounds that I haven't tried yet. I will try to make it for other platforms too, if possible.

**Comment by naqushab** [comment]
Of course, appreciate the effort.
