### ISSUE TITLE
Import from file not working

### ISSUE THREAD

**Issue by Ffelon** [Sangwan5688/BlackHole#380]
### Discussed in https://github.com/Sangwan5688/BlackHole/discussions/379

<div type='discussions-op-text'>

<sup>Originally posted by **Ffelon** July 28, 2022</sup>
📌I can't import resso and Spotify playlist to black hole app.it showing failed.
![Screenshot_2022-07-28-21-16-38-359_com shadow blackhole](https://user-images.githubusercontent.com/110171852/181582753-5182fc93-6d82-40cb-8987-bc187ca901af.jpg)

![Screenshot_2022-07-28-21-16-08-805_com google android documentsui](https://user-images.githubusercontent.com/110171852/181582838-ccc91324-9e48-4e46-a5d3-5f0928e5d69c.jpg)

</div>

**Comment by Sangwan5688** [comment]
Import from file works only with playlists exported from blackhole itself. Use import from resso or import from spotify if you want to import them from those platforms.
