### ISSUE TITLE
No Offline Music Available

### ISSUE THREAD

**Issue by NS369** [Sangwan5688/BlackHole#388]
After updating to 1.15.1 'My Music' tab is empty. No offline (downloaded) songs from my Internal & SD card are showing in the music player.

**To Reproduce**
1. Go to 'Library'
2. Click on 'My Music'
3. Shows loading symbol....
![Screenshot_20220808-070447](https://user-images.githubusercontent.com/110795640/183321598-0eca1aae-4825-4c97-a113-21e2b910b6c4.png)

**Expected behavior**
All the downloaded songs in Internal & SD storage should be shown in 'My Music' tab.

**Device Details (please complete the following information):**
 - OS: Android
 - Version: Android 9
 - Device: Infinix S4
 - App Version v1.15.1

**App Logs**
NA

**Comment by Sangwan5688** [comment]
Make sure the app can access your local storage. Can be caused by permanent denial of storage access.

**Comment by NS369** [comment]
Permission is already granted Sir. It worked pretty well before 2 months.
But now no versions ( latest & older) can load offline music. PS - Not a
problem of my device (because all other music players & apps are perfectly
accessing device files)

**Comment by N-R-K** [comment]
I seem to have the exact same issue. None of the local music shows up (mp3, flac and opus encoded ogg) despite giving the app storage permission. Android 9 here as well.
