### ISSUE TITLE
add more sources

### ISSUE THREAD

**Issue by vehosah** [Sangwan5688/BlackHole#39]
**Is your feature request related to a problem? Please describe.**
yeah i want more sources

**Describe the solution you'd like**
i want you to add soulseek,nhaccuatui,chiasenhac,vk

**Describe alternatives you've considered**
i don't have any alternatives

**Additional context**

**Comment by Sangwan5688** [comment]
@vehosah It won't be possible for me to add these sources. Also, adding different-different sources then downloading from different-different and all that. It will be a mess. I understand the need for another source as there's mostly Indian music right now with the current source. So, I'm thinking to add youtube as a source (#35) that has a large database and there won't be any need for another source then.

**Comment by vehosah** [comment]
The problem with YouTube is that it has shit quality

Στις Δευ, 28 Ιουν 2021, 4:36 π.μ. ο χρήστης Ankit Sangwan <
***@***.***> έγραψε:

**Comment by Sangwan5688** [comment]
@vehosah I understand the fact, but there isn't any source right now, that might have a huge collection of worldwide songs with good quality. If I ever find something good then I will surely implement it in the app.

**Comment by vehosah** [comment]
I know a lot, vk, soulseek

Στις Τρί, 29 Ιουν 2021, 9:15 π.μ. ο χρήστης Ankit Sangwan <
***@***.***> έγραψε:

**Comment by Sangwan5688** [comment]
I think you didn't understand it the first time. I can't add these types of sources. If you know of any `API` then lemme know but can't add any such platform.
