### ISSUE TITLE
Low quality image with local music

### ISSUE THREAD

**Issue by Anslem27** [Sangwan5688/BlackHole#402]
*Whenever I play any song from my local music, all the cover art loses quality, don't know whether it's the cache problem, but sure even previous versions have this.*

![Screenshot_20220907-205821](https://user-images.githubusercontent.com/89728185/188947085-10f3efb1-54c1-4777-bc6f-439dbe86d745.jpg)
![Screenshot_20220907-205816](https://user-images.githubusercontent.com/89728185/188947112-e15b698f-ac5a-4f28-be12-f713af8d29c7.jpg)
![Screenshot_20220907-205320](https://user-images.githubusercontent.com/89728185/188947118-b951c97d-67b4-4d3b-8bc5-0386aac78fb5.jpg)

*Under normal circumstances it should look like this(clear image  art in other words)*
#### alternative player  👇

![Screenshot_20220907-205839](https://user-images.githubusercontent.com/89728185/188947269-3054ce26-85ce-4904-aed6-e11fa7df7572.jpg)

 - OS: Oxygen OS 11 Android 11
 - Device: OnePlus 
 - App Version [v1.15.2]

**Comment by Sangwan5688** [comment]
Fixed with the latest commit
