### ISSUE TITLE
Ios side youtbe section is not working 

### ISSUE THREAD

**Issue by kaushikgodhani** [Sangwan5688/BlackHole#404]
**Describe the bug**
When we go to youtube section and trying to playsong some time is working and some time not working this issue facing online ios device

**To Reproduce**
1. Go to Home
2. Click on Youtube
3. Click on Punjab fire and 1st guru Randhawa song not working while We Rollio Song playing

**Screenshots**
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-09-11 at 10 54 14](https://user-images.githubusercontent.com/8804242/189513800-b3a38030-95df-4f6b-85e1-3ad58b165859.png)
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-09-11 at 10 56 55](https://user-images.githubusercontent.com/8804242/189513807-c7f12b5f-219b-48d6-80f3-4e79eaa96601.png)
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-09-11 at 10 57 02](https://user-images.githubusercontent.com/8804242/189513809-e1fb0ac0-0141-4ffb-9035-6eb4d1c91b1d.png)
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-09-11 at 10 57 11](https://user-images.githubusercontent.com/8804242/189513810-0bc28d1a-d170-4401-95b7-32387af67db8.png)

**Device Details (please complete the following information):**
 - OS: IOS
 - Version: IOS 15.5
 - Device: iPhone 13 pro max
 - App Version [e.g. v1.13.0]

**Comment by Sangwan5688** [comment]
Fixed with latest commit
