### ISSUE TITLE
[Help Wanted] Extend app for iOS

### ISSUE THREAD

**Issue by Sangwan5688** [Sangwan5688/BlackHole#42]
As we know to extend the app for iOS we need a MacBook and at least some knowledge in iOS App development. I have neither of them. Even if I have it will take some time. I know there are ways to build iOS app without Mac using some websites. But I was encountering a lot of issues and couldn't even build the app. So, if you have Mac and knowledge in app development. Feel free to open a PR. Thanks in advance :)

**Comment by AJAYK-01** [comment]
> As we know to extend the app for iOS we need a MacBook and at least some knowledge in iOS App development. I have neither of them. Even if I have it will take some time. I know there are ways to build iOS app without Mac using some websites. But I was encountering a lot of issues and couldn't even build the app. So, if you have Mac and knowledge in app development. Feel free to open a PR. Thanks in advance :)

Hello!!
Thank you for making this awesome project!
I tried running the app in the ios simulator, and the errors are from the firebase packages. Have you registered the iOS app in your firebase project? The android and ios both have to be registered, I couldnt find the ```GoogleService-Info.plist``` file in the project which is similar to the ```google-services.json``` file for android

**Comment by Sangwan5688** [comment]
@AJAYK-01 No, I haven't done firebase configuration for the iOS side. You can just create your own firebase and add files. I'm not familiar with the iOS side that much and I don't even have anything to test.

**Comment by Fernando321438** [comment]
Which pages need to be changed to start the music on IOS devices?

**Comment by BechirAhmed** [comment]
@Fernando321438 as i think the biggest IOS problem is download and listen offline, do you have any solution ?

**Comment by Fernando321438** [comment]
@BechirAhmed  Unfortunately, it has not been a week since I have been arguing with it but I have not found working solutions :/

**Comment by Fernando321438** [comment]
@BechirAhmed  Unfortunately I have been arguing with us for a week but I have not found working solutions: /

**Comment by Sangwan5688** [comment]
@Fernando321438 app works fine without download and offline section? As for offline section, you can completely remove it for iOS. Whereas for downloads, we will have to look over it but I guess the issue is just regarding download path. So, it can be resolved in future

**Comment by Sangwan5688** [comment]
Ok, so there have been some advances iOS Side. Thanks to @BechirAhmed for fixing the playback issue with an unexpected workaround and thanks to @Surendrajat for compiling and exporting IPA file for installation.
So, finally the ipa file is ready but there are some issue with the installation. Looks like iOS isn't allowing the app to be installed coz it's not from a trusted developer (obviously coz we don't have iOS developer account). I'm not able to attach the ipa file here so I'm just adding a link to the file in telegram you can download from there.

Link to IPA File: https://t.me/blackhole_official/102

Error shown:
![photo_2021-12-20_09-41-36](https://user-images.githubusercontent.com/42967322/146710788-feb0b537-d721-4346-8185-d066570e0195.jpg)

#### So what to do now
If anyone is able to install this IPA file with a way or two then do let us all know, It will really help. Additionally if anyone has access to an apple developer account then please try compiling and exporting the app. If are unable to compile then do comment here so that we can help with the same.

**Comment by CommanderEntropy** [comment]
> #### So what to do now
> If anyone is able to install this IPA file with a way or two then do let us all know, It will really help. Additionally if anyone has access to an apple developer account then please try compiling and exporting the app. If are unable to compile then do comment here so that we can help with the same.

Thanks for all the hardwork that you guys have done. 

I have downloaded and installed BlackHole on my jailbroken iPad Air 1 running iOS 12.5.5 by sideloading it using Filza. You guys can ask me stuff and I'll try my best to answer.   

Appreciate the effort you guys have put in. I have included a recording and a screenshot. (Screen recording's a bit choppy because the iPad is quite old. Sorry 🥲)

https://user-images.githubusercontent.com/83172580/147160766-b21356ca-101e-4885-801b-3debf0012c86.MP4

![IMG_1055](https://user-images.githubusercontent.com/83172580/147160782-4f08c4b9-84e8-4c6d-977b-cc4f8cbb6c23.jpg)

**Comment by Sangwan5688** [comment]
@CommanderEntropy Thanks for confirmation. And about installation, as of now I have found 3 ways which are as follows:
1. Using AltStore (as suggested by @CommanderEntropy). It think it will be the best solution as of now but I still haven't got any confirmation from anyone that it does work using altstore or not.
2. Someone used a software called `Sideloadly!` on Windows to sideload it. You just have to enter your apple id and all. It's same as AltStore as far as I heard. The app does work that way but again I don't have any confirmation about the 7 days license validation. If user does have revoke it every week (which i suppose is the case), then I think AltStore will be a better option.
3. Finally, If you have JailBroken iOS. There are tons of ways then.

As for releasing IPA file publicly, from next version on-wards, I will release Android, iOS and Windows all together on GitHub. Let's hope for Linux too :)

**Comment by CommanderEntropy** [comment]
@Sangwan5688 There is another to install and that's by using profiles. Basically in Safari, if a user tries to download a configuration profile it allows them to install any app (Verified, Unverified, etc)

They don't expire as far I know so the user doesn't have to worry about the app "expiring." 

I don't know how updates would work with this method. Would probably require a reinstall every time.

**Comment by Fernando321438** [comment]
It turns out to you not all the songs are being played for IOS devices

https://user-images.githubusercontent.com/62659188/149926301-96832529-07ec-4931-850b-63a3144f8226.mov

?

**Comment by Fernando321438** [comment]
I start the app on Ios and the music starts with a lot of delay and the error it gives me on xcode is the following: boressl_metrics_log_metric_block_invoke (151) Unable to record metrics

**Comment by Sangwan5688** [comment]
Ok, so as the iOS app has been released in latest version, I will be closing this issue. If someone is facing any bug or something then please create a different issue. This issue was just for the development of iOS version which has been accomplished.
