### ISSUE TITLE
Android APK

### ISSUE THREAD

**Issue by Tanmay221106** [Sangwan5688/BlackHole#420]
Android ka 3 apk hai latest version ka difference kya hai tino ma

**Comment by TheGuyDangerous** [comment]
Basically, a given Android device might have an arm or an x86 cpu (or even something else but that's not important), these are just different architecture types from different manufacturers. Arm cpus are most common, so when you compile a code, the output depends on the architecture target. 

Within a given architecture type there are multiple versions. armeabi-v7a is the older target, for 32 bit arm cpus, almost all arm devices support this target. arm64-v8a is the more recent 64 bit target (similar to the 32-bit -> 64 bit transition in desktop computers). I think most new devices are 64 bit, but not sure. arm64-v8a devices can run code compiled against armeabi-v7a, it's backwards compatible.
