### ISSUE TITLE
Podcasts not working, message displaying: error unsupported type show. 

### ISSUE THREAD

**Issue by Dhwani1i** [Sangwan5688/BlackHole#426]
**Describe the bug**

**To Reproduce**
3. Do this and that

**Expected behavior**

**Screenshots**

**Device Details (please complete the following information):**
 - OS: [e.g. Android, Windows, iOS, Linux]
 - Version: [e.g. Android 12, iOS 15, Windows 11 20H2]
 - Device: [e.g. Pixel 4, iPhone 13]
 - App Version [e.g. v1.13.0]

**App Logs**
If possible please provide app logs here.

**Comment by Sangwan5688** [comment]
fixed in latest version
