### ISSUE TITLE
No longer on F-Droid

### ISSUE THREAD

**Issue by flleeppyy** [Sangwan5688/BlackHole#433]
**Describe the bug**
The app isn't on f-droid anymore

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/18307183/197616328-d4fc67fc-0cfe-47b9-82ba-af3443adbbc3.png)
![image](https://user-images.githubusercontent.com/18307183/197617051-ac32dbb2-2b23-49b5-8480-56eacf2624f7.png)

**Device Details (please complete the following information):**

**App Logs**

**Comment by BrightDV** [comment]
Yes, because of some packages...
Also, duplicate of #395

**Comment by Sangwan5688** [comment]
This is now resolved. Will soon be available there.
