### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by HarshRi30** [Sangwan5688/BlackHole#436]
Its good how it has lyrics of most of the song but just a suggestion that some songs which are hindi-punjabi mix you it shows mix language, well you can separate it by different language option or like it can just take from web integration  whatever you do and like just a issue that when youve opened lyrics and the song changes it still shows the previous song lyrics, just consider fixing it in the uodate 
btw great app, keep it up
loved it!

**Comment by Sangwan5688** [comment]
Fixed with latest commit 528718e
