### ISSUE TITLE
Playing music issue album image doesn't changes

### ISSUE THREAD

**Issue by tanojsaipraveen** [Sangwan5688/BlackHole#44]
**Describe the bug**
When whenever the song completed next song will be loaded but the album image does not changes

**Comment by Sangwan5688** [comment]
Is this issue in the official release, v1.7 ??, or in the commit?

**Comment by tanojsaipraveen** [comment]
Bug is on main branch

**Comment by Sangwan5688** [comment]
should be resolved with 51832bf, lemme know if not
