### ISSUE TITLE
Let the greeting be case sensitive to user's input?

### ISSUE THREAD

**Issue by amog787** [Sangwan5688/BlackHole#446]
Ref: https://github.com/Sangwan5688/BlackHole/blob/13f8945db483aad2c76d60a0dadd1bf51595cf07/lib/Screens/Home/home.dart#L695

My suggestion is to let user be case sensitive about the first name they put in. Like some would want all in small case ;-;

**Comment by Sangwan5688** [comment]
done with latest commit
