### ISSUE TITLE
Layout issue in now playing screen

### ISSUE THREAD

**Issue by tanojsaipraveen** [Sangwan5688/BlackHole#46]
Bottom overflow by 20 px in now playing screen
![Screenshot_20210625-064131](https://user-images.githubusercontent.com/47939411/123354165-b25e8080-d580-11eb-8703-0f01bfa04375.jpg)

**Comment by Sangwan5688** [comment]
Ya, I'm familiar with the issue. It is caught by the mini-player plugin. I'm not sure what's causing the issue but as it was only visible when you are on the home screen and doesn't cause any issue in the released apk. So, I just ignored it. I will look for the real problem and fix it soon.

**Comment by tanojsaipraveen** [comment]
Great,Can you implement album search in the app so that we can search album wise songs

**Comment by Sangwan5688** [comment]
@tanojsaipraveen Album search has been implemented in v1.8. You can update your app and check. The top charts are from Spotify not from JioSaavn. And I would suggest If you have any query or doubt please use discussions or join the telegram group. The Issues section is just for issues.
