### ISSUE TITLE
Add Hindi Punjabi to Translated languages in Readme

### ISSUE THREAD

**Issue by ShareASmile** [Sangwan5688/BlackHole#473]
I have added "hi" & "pa" Punjabi(Indian) localization of app strings through weblate couple of weeks ago which is going to be included in this coming release.

However i didn't find any mention of both languages in the Readme.
Maybe I am missing something!

Would you please include it, Thanks by the way for great app.

**Comment by Sangwan5688** [comment]
Readme languages are different than in-app language which is being translated using weblate.

**Comment by ShareASmile** [comment]
Ok, now things are clearer
