### ISSUE TITLE
Showing as null

### ISSUE THREAD

**Issue by vinothkarthi** [Sangwan5688/BlackHole#483]
**Describe the bug**
Hi thank you so much it is super cool app. Issue is under the song name null value is displaying. If try to play that song it's not playing after this if I try to some other songs that songs also not playing 

**To Reproduce**
1. Go to 'Home Screen'
2. Click on 'Search and play Adi Penne song'
3. Try to play that song and after try to play some other songs 

**Expected behavior**
Instead of null we have display song details and song need to play

**Screenshots**
![Screenshot_2023-01-06-23-46-52-532_com shadow blackhole](https://user-images.githubusercontent.com/91256341/211074808-a1391f28-6e5b-4119-8721-a8da7accfaff.jpg)

**Device Details (please complete the following information):**
 - OS: Android
 - Version: Android 11
 - Device: Redmi Note 8 Pro
 - App Version: v1.15.5

**Comment by Sangwan5688** [comment]
Unable to reproduce. Is this happening only with this particular song?

**Comment by vinothkarthi** [comment]
Yes. Otherwise if u can able to play that song then come to the last session in that place u can able to see adi penne song. Now try to play. Here as well we can't able to see the song details. Thanks
![Screenshot_2023-01-07-10-41-22-030_com shadow blackhole](https://user-images.githubusercontent.com/91256341/211132314-ceff85d6-44bb-4cbf-bf93-dc42077992d0.jpg)
