### ISSUE TITLE
Location wise Music recommendations for users is a primary need 

### ISSUE THREAD

**Issue by asifmhdashik** [Sangwan5688/BlackHole#5]
Location wise Music recommendations for users is a primary need and this can result in user interest.Thank you

**Comment by Sangwan5688** [comment]
I have currently provided an option to select music language in the settings. Music of that language only will be shown on the home screen. But I know it is not sufficient and needs improvement. I am thinking to provide an option during the initial app startup to select language preferences.

**Comment by Sangwan5688** [comment]
Language-specific results as well as playlists have been added to the app. As far as location is concerned. It is possible, but I will have to ask for location permission and all. And I don't want to track user location just for location-specific songs. As language specifics are already there, you can just choose your preferred language. I am closing the issue now. Thanks for feedback :)
