### ISSUE TITLE
Make initial download quality of youtube video songs "Low"

### ISSUE THREAD

**Issue by Sudhanva-Nadiger** [Sangwan5688/BlackHole#502]
Currently, the app by default uses high-quality for youtube songs, which some users don't want,
So keeping the value low initially and if user wants high quality he/she can change it !
![image](https://user-images.githubusercontent.com/93595710/214883685-9bdc62f0-7de8-4a19-9272-fcd5a1fce0a7.png)

**Comment by Sudhanva-Nadiger** [comment]
@Sangwan5688  if this feature is okay can I work on this ?

**Comment by Sangwan5688** [comment]
I presume no one wants to download songs in low quality. That's why default download qualities are high. On the other hand, to save data, streaming qualities are low by default. I have no plans to change this default behavior.

**Comment by Sangwan5688** [comment]
I'm not sure if I have changed it or not, but i think youtube section always loads high quality songs, no matter what quality you set. You can check if that's the case or not & fix that if you want. You can also check if it downloads according to selected quality for youtube. I think downloads are also in high quality by default in youtube.

**Comment by Rafee-M** [comment]
@Sudhanva-Nadiger You may close this if your query has concluded and it seems like it has
