### ISSUE TITLE
search is not working 

### ISSUE THREAD

**Issue by thor1237666** [Sangwan5688/BlackHole#512]
**Describe the bug**

**Steps To Reproduce**
3. Do this and that

**Expected behavior**

**Screenshots**

**Device Details (please complete the following information):**
 - OS: [e.g. Android, Windows, iOS, Linux]
 - Version: [e.g. Android 12, iOS 15, Windows 11 20H2]
 - Device: [e.g. Pixel 4, iPhone 13]
 - App Version [e.g. v1.13.0]

**App Logs:**

**Comment by BrightDV** [comment]
If you live outside of India, are you using a VPN with an Indian server?

**Comment by Erz3** [comment]
Search work but all playlist and albums apear empty for me.

**Comment by BrightDV** [comment]
> Searchs work but all playlist and albums apear empty for me. Just work Youtube's music.

You have to use a VPN if you try to use it outside of India. This is a limitation from JioSaavn (the host). See [this comment](https://github.com/Sangwan5688/BlackHole/issues/52#issuecomment-894400639).
That is why albums & playlists are empty.

**Comment by Sangwan5688** [comment]
Closing this as the reason is already stated in the comment above
