### ISSUE TITLE
Song speed button

### ISSUE THREAD

**Issue by Didvino** [Sangwan5688/BlackHole#514]
is:open label:enhancement 
I thing you should change the position of song speed button,every time I try to change the song speed it ends the song by mistake becouse it is too close to the track line, it's really annoying

**Comment by DecodeAndCode** [comment]
I would like to Work on this issue can you assign it to me.

**Comment by Sangwan5688** [comment]
I doubt this is relevant anymore, I'll reopen if someone reports the issue
