### ISSUE TITLE
Streaming quality doesn't change 

### ISSUE THREAD

**Issue by DLC01** [Sangwan5688/BlackHole#521]
**Describe the bug**
Streaming quality seems to be fixed to 96kbps even though 320kbps is selected in the settings 

**Steps To Reproduce**
1. Go to settings 
2. Click on streaming quality and change it to 320kbps
3. try playing an song and check the song info page
4. the "Url" shows `https://aac.saavncdn.com/*/*_96.mp4` which is the 96kbps stream 

**Expected behavior**
The player should choose the 320kbps stream(`*_320.mp4`)

**Screenshots**
![Screenshot_2023-02-22-18-33-35-242_com shadow blackhole](https://user-images.githubusercontent.com/74525818/220627478-4f71bf69-410f-4fca-a221-02b7bedfe27c.jpg)

**Device Details (please complete the following information):**
 - OS: Android
 - Version: Android 10
 - Device: Redmi note 7 pro
 - App Version: V1.15.6

**App Logs:**

**Comment by Sangwan5688** [comment]
96kbps URL is passed around everywhere inside the app, but when you play it, it checks for the quality and modifies the URL accordingly before playing.
