### ISSUE TITLE
Widget not working

### ISSUE THREAD

**Issue by aryan78387** [Sangwan5688/BlackHole#523]
**Describe the bug**
The widget is just a black area. When you tap it, it opens the app. It doesn't display any playing song.

**Steps To Reproduce**
Just go to blackhole widget and place it.

**Expected behavior**
The widget should display currently playing song's artwork, name and progress.

**Screenshots**
![Screenshot_2023_0224_135842.png](https://user-images.githubusercontent.com/124393240/221130065-52f4de8b-5134-4716-b2f6-3c4e156973d7.png)

**Device Details (please complete the following information):**
 - OS: Android
 - Version: Android 13
 - Device: Iqoo z5
 - App Version 1.15.6

**Comment by Sangwan5688** [comment]
The widget still needs to be developed. It's still under development hence the case.
