### ISSUE TITLE
This is a fantastic application, I really love it. And suggestion is you should improve widget.

### ISSUE THREAD

**Issue by solankybasant** [Sangwan5688/BlackHole#524]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Rafee-M** [comment]
Hi, this isn't really a good enchantment request and you might want to consider closing it. 

If you have any specific suggestions feel free to open another issue.

**Comment by Sangwan5688** [comment]
The widget is still under development, closing this
