### ISSUE TITLE
App not working in android device

### ISSUE THREAD

**Issue by R-i-a-d-h** [Sangwan5688/BlackHole#531]
when  I run the app show me this Error 

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\MyProjects\flutter_projects\BlackHole\android\app\build.gradle' line: 51

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by omjogani** [comment]
@R-i-a-d-h Go to <b>android/app/build.gradle </b> file and modify as following...

Remove Below Code
```
signingConfigs {
        release {
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }
```
&
Replace 
```
buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
            shrinkResources false
        }
    }
```
with (Change release to debug)
```
buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            shrinkResources false
        }
    }
```

And It will work fine...

Thanks
-Om Jogani

**Comment by R-i-a-d-h** [comment]
thx it's work

**Comment by Rafee-M** [comment]
@R-i-a-d-h Could you close the issue if your problem has been solved
