### ISSUE TITLE
Spacing Issue in Search Screen & Minor Bug in Search Input Box 

### ISSUE THREAD

**Issue by omjogani** [Sangwan5688/BlackHole#532]
While Using the Application I got to know some issues that I can fix in the app, issues described below...

## Screenshots
<table>
  <tr>
    <td>Spacing between History Chips and <br/><b>Search On Youtube Statement</b></td>
     <td>After choosing Trending Chip, Cursor is <br/>not moving at the end of word automatically.</td>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/72139914/224478253-f5fd8525-2be8-4bda-8f4f-64dccced1dfe.jpg" width=270 height=520> </td>
    <td><img src="https://user-images.githubusercontent.com/72139914/224478260-350810c2-5df2-4de1-9e81-6fe648b06855.jpg" width=270 height=520></td>
  </tr>
 </table>

I am working on this issue to fix it!

Thanks
-Om Jogani

**Comment by Sangwan5688** [comment]
This is resolved ig, closing thread
