### ISSUE TITLE
Login JioSaavn account

### ISSUE THREAD

**Issue by GautamMKGarg** [Sangwan5688/BlackHole#536]
It would be great enhancement if we will be able to login our JioSaavn account in the app. In this way JioSaavn will be able to track what we are listening and it will be able to suggest similar songs to us as per our taste. Also, we will be able to listen our sync our playlist with jiosaavn. We will be able to mark songs, albums and playlist as favorite in jiosaavn account.
In short all our data will be in sync.

**Comment by Rafee-M** [comment]
You'd need a paid account and there's privacy concerns as well

**Comment by GautamMKGarg** [comment]
Jio Saavn is not paid, it's free. It's customer choice if they want to buy or not.
Regarding privacy, option can be given to user, if they want to sync or not.

**Comment by dmdhrumilmistry** [comment]
Most of the music is now available only to premium users. I don't see any point of integrating JioSaavn login feature to this project instead @GautamMKGarg you should use jiosaavn app directly.

> Jio Saavn is not paid, it's free. It's customer choice if they want to buy or not. Regarding privacy, option can be given to user, if they want to sync or not.
