### ISSUE TITLE
Add  Youtube and Youtube Music in the last session panel. 

### ISSUE THREAD

**Issue by Raif1** [Sangwan5688/BlackHole#553]
**Is your feature request related to a problem? Please describe.**
Whenever I want to listen to a youtube video again I must find it. So keeping it in the last session panel might be a clever idea.

**Describe the solution you'd like**
Add YouTube and YouTube Music listens to the last session panel. This can be added directly or another subpanel for YouTube can be added too.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by tejasbirsingh** [comment]
I am new to this repo but I checked the code and found that we explicitly check if the genre is youtube then we don't add it to recently played songs.
Can someone please explain why we have to do this ? It would be very nice to know.

Thanks.

**Comment by Sangwan5688** [comment]
YouTube songs expire after some time (6hrs). Coz of which there was a playback issue earlier. Now, the app has provision to handle expired YouTube links, so we can remove that check now. If you want you can create a PR for the same. Do test it from your end as well, that if it's working fine after you open the app again after 6hrs or not

**Comment by tejasbirsingh** [comment]
Hi @Sangwan5688. Thanks for explaining ! 
Yes, I would like to work on this. Please assign this issue to me. 

I have few questions before I start making the changes . There are 4 places where we check if the genre is not youtube - 
[Link-1](https://github.com/Sangwan5688/BlackHole/blob/8c5f7c09608296e00b922e905fd8244290ccbc52/lib/Services/audio_service.dart#L166), [Link-2](https://github.com/Sangwan5688/BlackHole/blob/8c5f7c09608296e00b922e905fd8244290ccbc52/lib/Services/audio_service.dart#L179), [Link-3](https://github.com/Sangwan5688/BlackHole/blob/8c5f7c09608296e00b922e905fd8244290ccbc52/lib/Services/audio_service.dart#L260), [Link-4](https://github.com/Sangwan5688/BlackHole/blob/8c5f7c09608296e00b922e905fd8244290ccbc52/lib/Services/audio_service.dart#L559).

Link 1 - _We are checking if its is not youtube before storing in recently played list._
Link 2 - _It is handling auto play related logic._
Link 3- _We are checking if the first song is not of genre youtube in the lastQueueList while loading._
Link 4 - _It is checking the genre before saving the queue in cache._ 

I think only first check (link 1) can be removed to get the youtube songs added to recently played tab and 3rd and 4rd checks are related to the song we save in cache to which we were listening and it was not over yet. I am still new so I may be wrong please correct me in such case. I will do the testing as suggested by you before raising PR.

**Question** - **Should I removed the check from link-1 only or all of the link 1,3 and 4 ?** 

Thanks to you and contributors for providing and improving this wonderful app !
