### ISSUE TITLE
Make available in app store

### ISSUE THREAD

**Issue by lrperlmu** [Sangwan5688/BlackHole#554]
**Is your feature request related to a problem? Please describe.**
I am looking for an open source music player for iOS, and black hole comes highly recommended, but my iPhone is not jailbroken, so there is no way for me to install it.

**Describe the solution you'd like**
My request is to make black hole availble in the app store.

**Describe alternatives you've considered**
I considered jail breaking my iPhone, but it seems more difficult than finding another music player app, but the other app will probably be worse than black hole.

**Additional context**
n/a

**Comment by Sangwan5688** [comment]
Use AltStore/Sodeloadly/Scarlet to sideload the app on iOS. You can get BlackHole ipa file from GitHub releases or from the website
