### ISSUE TITLE
Spotify playlists and search does not work

### ISSUE THREAD

**Issue by Green0wl** [Sangwan5688/BlackHole#563]
**Describe the bug**
Spotify playlists and search doesn't work. Whereas YouTube Music and YouTube are fine. I don't know where the Trending Now tracks come from, but from the playlists they are the only ones that work. Radio stations are not functioning either. 

**Steps To Reproduce**
1. Go to Application 
2. Click on Top Charts playlist.

**Expected behavior**
Spotify music library search and radio playlists work.

**Screenshots**
![Screenshot_2023-04-25-16-46-47-134_com.shadow.blackhole.jpg](https://user-images.githubusercontent.com/72041440/234321146-d422b5ee-1875-4266-a8d6-a2539915ac01.jpg)

![Screenshot_2023-04-25-16-47-02-823_com.shadow.blackhole.jpg](https://user-images.githubusercontent.com/72041440/234321147-d5dac511-20fa-40d6-8eb0-82429fbf4b62.jpg)

![Screenshot_2023-04-25-16-46-34-493_com.shadow.blackhole.jpg](https://user-images.githubusercontent.com/72041440/234321148-5726b068-a2ee-4372-a9e2-393d701abd08.jpg)

Application logs when starting the application and when trying to click on the "Listen" button in non-working playlists, respectively:

![Screenshot_2023-04-25-16-57-37-899_io.github.mthli.loglog.jpg](https://user-images.githubusercontent.com/72041440/234321584-b285078c-a794-437a-8d33-c55cb10f80ba.jpg)

![IMG_20230425_170723.jpg](https://user-images.githubusercontent.com/72041440/234321625-573a7c76-d8ef-42de-94f0-b320f00ed480.jpg)

**Device Details:**
 - OS: Android, MIUI 12.5 (12.5.15.0 Stable)
 - Version: Android 11
 - Device: Rooted Xiaomi Redmi Note 8 Pro.
 - App Version: From F-Droid. 1.15.7

**Comment by Green0wl** [comment]
Yes, indeed - I showed the JioSaavn playlists, not Spotify. That was my mistake, but after searching through the playlists a bit, I couldn't find any from Spotify. All just from JioSaavn.

I scrolled through all the playlists that are available to me on the home page, and here are the results:

The situation in Trending Now is very strange. Some playlists load and some don't. But most of them contain only one track. And those tracks (individual - not in playlists), which were downloaded a month, maybe a month ago, still hang and not updated. Some of the playlists that contain only one track: Dreamers [Music from the FIFA... (I can't see the name further down), My Stupid Heart (Kids Version), Calm Down and others. But at the same time some of the playlists look really good: "Bebe" (contains 12 songs by Bebe Rexha), "Guardian Of The Galaxy Mixtape..." (I can't see the title any further: 16 songs by New Tribute Kings), "- (Deluxe)" by Ed Sheeran - 18 songs. Also "Starboy (Deluxe)": 21 songs from The Weekend. And that's probably all the playlists that contain more than one song. Some of the playlists that contain nothing: Chartbusters 2022 - English, "Most Streamed Love Songs - ...", English: India Superhits Top 50, and others.

At the moment, nothing works in Top Charts except one playlist with one track: "English 2010s" with the track "DJ Bravo Champion".

New Releases is not updated. Although they also have filled playlists, like "Diamonds & Dancefloors".

Editorial Picks: almost nothing works. Everything is blank, except for some exceptions. Neither does Fresh Hits, along with Summer 2023.

Like I said, I couldn't find any Spotify playlists. all from JioSaavn.

The radio stations are completely non-functional, as well as from the proxy built into the app I do not see results.

I plugged in Rethink DNS, and looked at the addresses BlackHole uses when I try to click on playlists: 

When loading:
![IMG_20230508_182805.jpg](https://user-images.githubusercontent.com/72041440/236879626-a302a74e-384c-4cc8-bf83-6322589dbbf9.jpg)

When you click on any of the playlists (whether they work or not), and the radio; it's all used together:
![IMG_20230508_182901.jpg](https://user-images.githubusercontent.com/72041440/236879659-922f5865-22c6-419a-b6f5-3926cedfeab0.jpg)

I haven't used the VPN server in India yet, but I tried it with Orbot: nothing has changed. 

Thank you!

**Comment by hegdenischay** [comment]
Okay some of the "playlists" that you mentioned are actually albums, like the Guardians of the Galaxy thing:
![playlist](https://user-images.githubusercontent.com/28584388/237003496-ec59639e-670f-4d45-8637-fafbf17a7816.png)

That makes me think that maybe only JioSaavn playlists are not showing up on your end. And you're right, this app can't find Spotify playlists in the home page, only JioSaavn playlists.

Also, I did some digging on the website end, and it looks like jiosaavn.com simply doesn't show some playlists on Tor, which makes me think this stuff is IP limited to India

On Tor:
![image](https://user-images.githubusercontent.com/28584388/237005160-137ee3b7-4a1f-4eb2-8a89-f36fa2b1c349.png)

On Firefox:
![image](https://user-images.githubusercontent.com/28584388/237005491-ab3c2da8-478f-4214-8e09-a20557f0fda3.png)

**Comment by BrightDV** [comment]
I had the same issue some days ago but now the playlists are showing fine again. However, you must have a VPN set to India to be able to see the playlists and search for songs. JioSaavn is geo-restricted for english songs (for copyrights issues I guess). I tried with Tor too and I could not make it working.

**Comment by Green0wl** [comment]
Yes, indeed, almost everything works with the VPN - only the standard search (not by YouTube, and YouTube Music) is not working. Everything else works great: radio, albums and playlists of all categories. Thank you! What could be the problem with searching?

**Comment by BrightDV** [comment]
> only the standard search (not by YouTube, and YouTube Music) is not working.

Can you elaborate, have you an example query which is not working? The search is fully functional on my end, however, it is very sensitive to spelling mistakes.
<img src="https://github.com/Sangwan5688/BlackHole/assets/92821484/57799b5d-035d-4904-a986-2b8bd1234e0b" width=200px>

**Comment by Green0wl** [comment]
This is a rather strange thing - it really only works flawlessly if the application's internal default proxy (103.47.67.134:8080) is disabled.

Meaning:
VPN enabled + proxy disabled in the app = everything works.
![IMG_20230510_201917.jpg](https://github.com/Sangwan5688/BlackHole/assets/72041440/9f142135-f196-4e89-881e-38d3e23db161)

Enabled VPN + enabled proxy in the app = everything works except search (infinite download).
![IMG_20230510_201848.jpg](https://github.com/Sangwan5688/BlackHole/assets/72041440/89124bd4-762c-4de0-830b-5c50a4f97613)

![IMG_20230510_201826.jpg](https://github.com/Sangwan5688/BlackHole/assets/72041440/4c648ed0-9a2d-4989-9bcb-ade64444bb42)

I would like to differentiate between these 2 things - when VPN is on, everything starts working very slowly. In fact, I can connect VPN only for some apps, but then all the others will remain without ad blocking and RethinkDNS, for example. The solution, it seems to me, lies in the proxy, but it doesn't work. I also tried to connect other proxies, but either I do something wrong, or they do not work, or some bugs.

**Comment by BrightDV** [comment]
> I would like to differentiate between these 2 things - when VPN is on, everything starts working very slowly. In fact, I can connect VPN only for some apps, but then all the others will remain without ad blocking and RethinkDNS, for example. The solution, it seems to me, lies in the proxy, but it doesn't work. I also tried to connect other proxies, but either I do something wrong, or they do not work, or some bugs.

I got the same issue when I started using the app. The proxy is very unstable, and I could not make it working (I just tried with different proxies, and it did not work). The best you can do is only enabling your VPN when you search for songs, like them, and finally re-enable RethinkDNS. Then, you will be able to play those songs without a VPN, but I agree that it is not very convenient.

**Comment by hegdenischay** [comment]
I am not sure what RethinkDNS is, it looks like some sort of a local VPN that allows custom blocklists.

I personally use NextDNS as a part of the secure DNS option in the android settings and you can use other VPNs on top of it.

Also, the proxy IP that's used as default is a residential IP, so I'm going to assume @Sangwan5688 personally hosts it. The best compromise imo would be to use another Indian IP as a proxy, or using NextDNS + third party VPN.

**Comment by Green0wl** [comment]
I will definitely try NextDNS! After breaking my head a bit on how to arrange it all together, I came to the best option: SagerNet. I built several proxy routes that can work independently of each other and without affecting all other applications, and then wrapped it all in an orbot without vpn mode. Also, I found some free (and, of course, insecure) Indian vpn server at https://www.vpnjantit.com/, but in this case, the security of this server is not important, because now BlackHole uses its own separate vpn route (only, you will have to update it every week - for this I downloaded v2ray VMess on this site, and then using v2rayng the android application created a new configuration by "url from the clipboard", which I then transferred to SagerNet using the "share" button; works). And for everyone, you can use PCAPdroid (request tracking only), which works without a VPN, and completely in commonwealth with everything mentioned above, completes the RethinkDNS functionality. To sum up, now I can see all the requests of my android, BlackHole is running its own Indian VPN on its own router, and everything else is wrapped in Tor. Unnecessary applications or dangerous ip applications can be blocked by the same routers that go to a known non-working proxy, or vice versa - freed from all this routing so that they work on their own; for example, this opportunity must be given to Orbot, otherwise the cycle closes, and Orbot transfers its own data to itself without going online. I think to you, @BrightDV, this option might be interesting, so as not to switch vpn every time you download playlists or albums, and then return it all back to its place.

**Comment by BrightDV** [comment]
Thanks **a lot**! I reproduced these steps and can now use BlackHole without switching every time between the VPNs!
However, did you manage to use BlackHole's rule in proxy mode/without using Android's VPN?
NextDNS seems to be a good compromise with an easier setup, though.

**Comment by Green0wl** [comment]
No, I was not able to use the built-in proxy function in the BlackHole app. The main problem with using proxies in the app was that I could not find a proxy without user authorization, and the network user authorization in the BlackHole app, and in particular in the proxy function, is not supported. It might be possible to find a way to use the built-in proxy connection feature, but, I'm quite happy with all the flexible, albeit, slightly tricky settings that come out now. Thank you!

**Comment by BrightDV** [comment]
I think this should be closed, as the latest version brings a fully functional proxy.

**Comment by Green0wl** [comment]
thanks for the message! everything works just fine!
