### ISSUE TITLE
Can't build app

### ISSUE THREAD

**Issue by philipxlima** [Sangwan5688/BlackHole#573]
![image](https://user-images.githubusercontent.com/79344102/236578260-1785c9a0-9fb3-4295-a52f-4ee9c878124e.png)

**Comment by vijaykarthiktk** [comment]
#591

**Comment by vijaykarthiktk** [comment]
#591 Same Issue(Solved)

**Comment by Sangwan5688** [comment]
Please take master merge, closing this
