### ISSUE TITLE
Favorites (YouTube) are not played

### ISSUE THREAD

**Issue by YakovL** [Sangwan5688/BlackHole#578]
**Describe the bug**
I've added several YouTube tracks to favorites. Howerver, they are not played.

**Steps To Reproduce**

1. Find a YouTube track, play it (make sure it plays: not all of them do!), add it to favorites
2. Wait some time (can't say for sure, for me it was ~24h or more; just closing and opening the app is not enough)
3. Open app, click on favorites on the main screen, click the added favorite track.

**Expected behavior**
The chosen track plays.

**Actual behavior**
It doesn't. See the log above, it says the link has expired, but the video is definitely still there.

**Device Details (please complete the following information):**
 - OS: Android 10
 - Device: Armor X7 Pro
 - App Version: 1.15.5 (looks like it's the latest in F-Droid, although I can see that the latest release here is 1.15.7)

**App Logs:**

INFO: 2023-05-13 23:05:54.267325: record.message: youtube link expired
record.error: null
record.stackTrace: null

**Comment by Sangwan5688** [comment]
Please make sure you are using the latest version of the app.
