### ISSUE TITLE
Lots of problems from the beginning.

### ISSUE THREAD

**Issue by nothingness6** [Sangwan5688/BlackHole#580]
I faced lots of problems when I opened it up. Especially, lots of "unknown word" messages. It had 10k + problems in the beginning and reduced to 80 since I typed "flutter pub get". 
I have no clue as I'm very beginner for Flutter and Dart. 
Here are the screenshots:
![flutter-01](https://github.com/Sangwan5688/BlackHole/assets/105210258/f4b435ed-f18c-4789-8b25-5288dae2959e)
![flutter-02](https://github.com/Sangwan5688/BlackHole/assets/105210258/7972fd20-40e7-4ff4-b33a-f381991dead9)
![flutter-03](https://github.com/Sangwan5688/BlackHole/assets/105210258/223f80cc-f8c0-4445-8e41-faf6cff21ecb)

How do I fix it?

**Comment by Sangwan5688** [comment]
You are probably using some extension for spelling check or something. Errors irrelevant to the project, closing issue
