### ISSUE TITLE
"SearchBar" isn't a function

### ISSUE THREAD

**Issue by nothingness6** [Sangwan5688/BlackHole#591]
**Describe the bug**
The error message says, "SearchBar isn't a function. Try correction the name to match an existing function, or define a method or function named SearchBar"

**Steps To Reproduce**
1. It just happens when I open it. 
3. Do this and that

**Expected behavior**
It's supposed to work without error. 

**Screenshots**
![Blackhole-01](https://github.com/Sangwan5688/BlackHole/assets/105210258/0940e58b-be7c-41fc-b2f9-ec934445ba13)

**Device Details (please complete the following information):**
 - OS: [e.g. Android, Windows, iOS, Linux] Windows
 - Version: [e.g. Android 12, iOS 15, Windows 11 20H2] Windows 10 64bit 22H2 
 - Device: [e.g. Pixel 4, iPhone 13] Lenovo Laptop
 - App Version [e.g. v1.13.0]  1.15.7

**App Logs:**

**Comment by vijaykarthiktk** [comment]
Change the import as like this .
![image](https://github.com/Sangwan5688/BlackHole/assets/39937989/b4b55bdd-af37-4ad0-99be-6abfe5aa49d7)
And use the Widget like this.
![image](https://github.com/Sangwan5688/BlackHole/assets/39937989/ee72da49-90b1-4440-be9a-3cf6c4c92ddd)

**Comment by nothingness6** [comment]
> Change the import as like this . ![image](https://user-images.githubusercontent.com/39937989/242236916-b4b55bdd-af37-4ad0-99be-6abfe5aa49d7.png) And use the Widget like this. ![image](https://user-images.githubusercontent.com/39937989/242237468-ee72da49-90b1-4440-be9a-3cf6c4c92ddd.png)

Great! It removed the error from search.dart, but there are still many errors at youtube.search.dart. Here is the screenshot:
![Blackhole-02](https://github.com/Sangwan5688/BlackHole/assets/105210258/70625a56-eb53-445d-b22a-656f68d7224c)

**Comment by Sangwan5688** [comment]
@nothingness6, you need to take the master merge. These errors were resolved a long time ago.

**Comment by nothingness6** [comment]
> @nothingness6, you need to take the master merge. These errors were resolved a long time ago.

Do you mean merge the search.dart and youtube_search.dart?
