### ISSUE TITLE
SnapChat Sharing Feature is Not available

### ISSUE THREAD

**Issue by Ansalpandey110043** [Sangwan5688/BlackHole#592]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Rafee-M** [comment]
Could you explain the issue?

**Comment by Ansalpandey110043** [comment]
Sorry for the late reply, I was just exploring the GitHub features.
You can delete this issue.
