### ISSUE TITLE
Filters not Working

### ISSUE THREAD

**Issue by mystic-man-rhino** [Sangwan5688/BlackHole#593]
Except for first Tab of My Music, Downloads rest of filters (album, artist etc) not working.

**Comment by vijaykarthiktk** [comment]
No bug found working fine.

https://github.com/Sangwan5688/BlackHole/assets/39937989/eebb68c1-5071-42ab-913d-2eca5a03909b

**Comment by mystic-man-rhino** [comment]
What I meant is filters such as Sort by Name, Date, Artist etc not working in tabs other than "Songs"

**Comment by mystic-man-rhino** [comment]
[Video](https://drive.google.com/file/d/1HPV3Sf8TIE9jKG_dCLcUUwtxHw2CsHhU/view?usp=drivesdk)
