### ISSUE TITLE
Unable to install BlackHole: This app cannot be installed because its integrity could not be verified

### ISSUE THREAD

**Issue by Frank-Mayer** [Sangwan5688/BlackHole#595]
I tried to install BlackHole on my iPhone using the ipa file from the GitHub Release v1.15.7 ([fb54d36](https://github.com/Sangwan5688/BlackHole/commit/fb54d3631f8f95758370c7553fe8658cd639ecf3))

macOS Ventura 13.4
XCode 14.3 (14E222b)

iPhone SE2
iOS 16.4.1

**Screenshots**
<img width="1154" alt="Screenshot 2023-06-02 at 10 33 39" src="https://github.com/Sangwan5688/BlackHole/assets/53651857/fa6e3f25-478b-418e-bb9c-6887fa3b3d92">

![IMG_4316FC90FE4A-1](https://github.com/Sangwan5688/BlackHole/assets/53651857/4412f1fd-74c2-4c4a-863f-b0fb995c6967)

**Comment by Frank-Mayer** [comment]
https://developer.apple.com/forums/thread/721443

**Comment by Sangwan5688** [comment]
https://techbeyondboundaries.com/blogs/install_ipa_on_iphone/

**Comment by Frank-Mayer** [comment]
Thanks, @Sangwan5688
