### ISSUE TITLE
SdCard support 

### ISSUE THREAD

**Issue by ratul0547** [Sangwan5688/BlackHole#60]
**No SdCard access is available yet in this cool app.**
 
Music library from SdCard is a key to any fully functioning music player app. But unfortunately this app can only read music from phone internal storage. It would be really nice if there is the function to add music to library from sdcard. 
Using SAF interface would be more preferable for Android 11 and later versions.
Best regards.

**Comment by Sangwan5688** [comment]
@ratul0547 Thanks for the issue, but I have already added SD Card support, a few days ago in the commit 1735f0b. It will be available there in v1.9 :)
