### ISSUE TITLE
Lyrics sync feature

### ISSUE THREAD

**Issue by rahul0x00** [Sangwan5688/BlackHole#600]
Hi, I would like to request the addition of a new feature to the app that allows for lyrics synchronization with the music playback. It's the basic feature that is missing

**Comment by AdiAr11** [comment]
Hi, where can we get the lyrics from? I can try to implement this feature if we can get lyrics

**Comment by rahul0x00** [comment]
Hi, you can get the lyrics from https://www.azlyrics.com/

**Comment by rahul0x00** [comment]
You can also try this api http://www.chartlyrics.com/api.aspx

**Comment by AdiAr11** [comment]
Thank you @rahul0x00

**Comment by Bagadeeshkumar** [comment]
refer to this also https://github.com/Sangwan5688/BlackHole/issues/274

**Comment by Sangwan5688** [comment]
This is already present. You need to make sure you are signed in with spotify to use that feature
