### ISSUE TITLE
Overflow error in Pref Screen, when use app turkish language

### ISSUE THREAD

**Issue by hasankarli** [Sangwan5688/BlackHole#629]
**Describe the bug**
When I go to pref screen, get overflow error

**Steps To Reproduce**

1. Open Blackhole
2. Go to Pref Screen

**Expected behavior**
I expected don't get overflow error. I got this error when app use Turkish language

**Screenshots**
<img src="https://github.com/Sangwan5688/BlackHole/assets/42219301/5f6e6c73-1841-4bb3-8e12-683ae3d6faf4" width="200">

**Device Details (please complete the following information):**
 - OS: iOS
 - Version: iOS 15.5
 - Device: iPhone 13
 - App Version  v1.15.8+39

**App Logs:**
```
A RenderFlex overflowed by 17 pixels on the right. 
The relevant error-causing widget was Row pref.dart:126  
```

**Comment by Sangwan5688** [comment]
My bad, mistakenly assigned to myself
