### ISSUE TITLE
After playing any song, bottom navigation bar is not visible, And getting warning bottom overflowed by 68pixel

### ISSUE THREAD

**Issue by avinashcoder** [Sangwan5688/BlackHole#636]
**Describe the bug**
After playing any song, bottom navigation bar is not visible, And getting warning bottom overflowed by 68pixel

**Steps To Reproduce**
1. Open app (a fresh start - uninstall and install again) Bottom navigation bar is visible
2. Play any song and come back on home screen. Bottom bar is not visible any more only miniplayer is visible

**Expected behavior**
Bottom bar should to be visible and UI warning "bottom overflowed by 68pixel" should  not come

**Screenshots**
![Screenshot_2023-07-16-16-31-32-43_a2df05e64545de9e48d383611b669e6e](https://github.com/Sangwan5688/BlackHole/assets/34886720/94ab221a-ef0c-4a57-9dce-76a1be297af5)
![Screenshot_2023-07-16-16-31-39-12_a2df05e64545de9e48d383611b669e6e](https://github.com/Sangwan5688/BlackHole/assets/34886720/898c2353-4ac4-4547-bfbb-f71ef6f33769)

**Device Details (please complete the following information):**
 - OS: [Android]
 - Version: [13]
 - Device: [Realme 8s 5g]
 - App Version [v1.15.8]

**App Logs:**

**Comment by Sangwan5688** [comment]
Closing this as it's no longer relevant
