### ISSUE TITLE
Artist profile from the now playing page

### ISSUE THREAD

**Issue by yesNOmaybe69420pogchamp69** [Sangwan5688/BlackHole#64]
Any plans on having clickable artist names in the now playing screen? It could then take us to their profile where we could see all their songs. Like, i wanna see all of Wowkie Da's songs

**Comment by Sangwan5688** [comment]
Sounds cool, will try to add soon

**Comment by ATTUNETV** [comment]
Hello sir wanted to discuss your mobile application with you !

**Comment by Sangwan5688** [comment]
@ATTUNETV you can join the telegram group. Link is already there, in the app settings as well as in the Repo README file. Use issues just for well issues
