### ISSUE TITLE
YouTube download issue

### ISSUE THREAD

**Issue by Mahad871** [Sangwan5688/BlackHole#643]
**Describe the bug**
Youtube download songs don't download completely and hence play only half

**Steps To Reproduce**
1. Go to youtube search and download song ' with love ~faris shafi '
2. Play it and download it.
3. Now when you play it from downloads the songs will not play completely and will skip to the next song automatically 

**Expected behavior**
The song should play completely when download like it's played online

**Device Details (please complete the following information):**
 - OS: Android
 - Version: Android 13
 - Device:  Pixel 5
 - App Version:  v1.15.8 

**App Logs:**
INFO: 2023-07-21 15:17:02.599617: record.message: starting audio service

INFO: 2023-07-21 15:17:02.612647: record.message: Received Intent initially: null

INFO: 2023-07-21 15:17:02.675573: record.message: setting isolateSendPort

etting quality

INFO: 2023-07-21 15:17:02.677147: record.message: player | wifi connected, changing quality to 320 kbps

SEVERE: 2023-07-21 15:17:06.202925: record.message: got null in getMusicHome for 'Top Charts'
record.error: null
record.stackTrace: null

 null
Tried calling: []("title")
record.error: null
record.stackTrace: null

INFO: 2023-07-21 15:17:33.819593: record.message: calling youtube search

INFO: 2023-07-21 15:17:40.528422: record.message: calling youtube search

INFO: 2023-07-21 15:17:51.877599: record.message: adding ZAKgHqHjei0 data to stats

g more songs

INFO: 2023-07-21 15:17:51.885876: record.message: caching last index and position

INFO: 2023-07-21 15:17:54.433414: record.message: Recieved recommendations: []

ylist
record.error: type 'Null' is not a subtype of type 'List<dynamic>' in type cast
record.stackTrace: null

INFO: 2023-07-21 15:17:56.039048: record.message: Preparing download for Vitamin D - Faris Shafi x Talal Qureshi

INFO: 2023-07-21 15:17:56.042169: record.message: Cached Download path is empty, getting new path

INFO: 2023-07-21 15:17:56.050515: record.message: New Download path: /storage/emulated/0/Music

INFO: 2023-07-21 15:17:56.051760: record.message: Getting App Path for storing image

INFO: 2023-07-21 15:17:56.052536: record.message: Creating audio file /storage/emulated/0/Music/Vitamin D - Faris Shafi x Talal Qureshi - Faris Shafi.m4a

INFO: 2023-07-21 15:17:56.083684: record.message: Creating image file /data/user/0/com.shadow.blackhole/cache/Vitamin D - Faris Shafi x Talal Qureshi - Faris Shafi.jpg

INFO: 2023-07-21 15:17:56.084935: record.message: Connecting to Client

oad url with preferred quality

INFO: 2023-07-21 15:17:56.656782: record.message: broadcasting download state

wnload

INFO: 2023-07-21 15:20:10.734339: record.message: Download complete, modifying file

INFO: 2023-07-21 15:20:12.994803: record.message: Started tag editing

quired

INFO: 2023-07-21 15:20:13.023793: record.message: Closing connection & notifying listeners

INFO: 2023-07-21 15:20:19.847358: record.message: stopping player

INFO: 2023-07-21 15:20:19.865250: record.message: caching last index and position

**Comment by Mahad871** [comment]
Mine is Google Pixel 5 , Andriod 13

**Comment by Sangwan5688** [comment]
Closed in 0877e8391bc6be8aeded1b41ceb7854125a61c80
