### ISSUE TITLE
Resso UI

### ISSUE THREAD

**Issue by SH20RAJ** [Sangwan5688/BlackHole#648]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sangwan5688** [comment]
I'm not really a fan of resso UI, so nope!

**Comment by SH20RAJ** [comment]
> I'm not really a fan of resso UI, so nope!

People are fan bro...

See

Resso introduced only premium plan for customers and believe  people use resso mainly for the UI.0..

And that will not be hard or so much time taking foor yu to create anther app or in same app with resso ...
the templates are already buid apis are already there just add a new feature...

Still it's your mood to do it or not  👍
