### ISSUE TITLE
Import playlist from JioSaavn

### ISSUE THREAD

**Issue by CaptainKnox** [Sangwan5688/BlackHole#65]
Can you consider adding the feature of importing playlist from JioSaavn?

**Comment by Sangwan5688** [comment]
Well importing User Specific Playlists won't be possible coz JioSaavn doesn't allow that. But you can search your playlist if it's public. I will add an option to add playlists from search results directly inside your playlists.

**Comment by CaptainKnox** [comment]
Playlists are public so I'll try searching. I thinking of adding the option to login, but that would defeat the purpose.

**Comment by Sangwan5688** [comment]
Login via JioSaavn won't be possible as JioSaavn doesn't provide anything like that
