### ISSUE TITLE
Yt download and other bugs

### ISSUE THREAD

**Issue by Zaxx69** [Sangwan5688/BlackHole#651]
1. I couldn't download yt music, it always stops halfway and sometimes it only shows 0kb file as downloaded, i can't play any yt music

2. Sometimes when i click on a song, it doesn't play immediately. It starts playing after 5 seconds and i am taking about downloaded songs

3. Backup doesn't work, i have to manually add the songs, upon downloading the new version

**Comment by Sangwan5688** [comment]
Closed with 0877e8391bc6be8aeded1b41ceb7854125a61c80
