### ISSUE TITLE
unable to play the songs that are added in the playlist for youtube

### ISSUE THREAD

**Issue by Jasmeet1411** [Sangwan5688/BlackHole#655]
The songs that are added for youtube are not being played and automatically all the songs stops immediately playing and then the app needs to be closed and then after all the other songs play as normal but still the songs from the youtube gets the same issue.

Except that request you to please add black color in the light UI.

**Comment by Supreme69X** [comment]
Same issue

**Comment by Venryx** [comment]
Seems to be the same as this issue: https://github.com/Sangwan5688/BlackHole/issues/661

I suggest consolidating there, since the original-post has more details (eg. replication instructions with example song, device details).

**Comment by Sangwan5688** [comment]
Please make sure you are using the latest version, this already got resolved in 1.15.9
