### ISSUE TITLE
Search history not showing in at home screen

### ISSUE THREAD

**Issue by Akianonymus** [Sangwan5688/BlackHole#66]
**Describe the bug**
Search history doesn't show up when search is accessed from home screen

**To Reproduce**
1. Go to home screen / initial screen
2. Tap on search bar

**Expected behavior**
It should previous search history as suggestions

**Smartphone**
 - Device: Poco X3
 - OS: Android 11
 - App Version: v1.9.0

**App Logs**
If possible please provide app logs here.

**Comment by Sangwan5688** [comment]
I haven't added it there coz of the following reasons:
1. It might not look good on the home screen.
2. The search bar on the home screen is different from other search bars. Unlike other search bars, it changes its width as well as position with respect to the scroll. As well as the text "Hi There," fakes away under that search bar. There were some complications there and wasn't possible to add the search history.

I had an idea of sending the user directly to the search screen when he taps the search bar. Then he can search songs there with all the history as well as trending searches. But I might not even implement it. Waiting for suggestion :)

**Comment by Akianonymus** [comment]
> I haven't added it there coz of the following reasons:
> 
> 1. It might not look good on the home screen.
> 2. The search bar on the home screen is different from other search bars. Unlike other search bars, it changes its width as well as position with respect to the scroll. As well as the text "Hi There," fakes away under that search bar. There were some complications there and wasn't possible to add the search history.
> 
> I had an idea of sending the user directly to the search screen when he taps the search bar. Then he can search songs there with all the history as well as trending searches. But I might not even implement it. Waiting for suggestion :)

I think the latter suggestion is good, sending the user directly to the search screen when he taps the search bar.

Maybe add a toggle in settings to keep both options.

**Comment by Sangwan5688** [comment]
Sorry was busy with other important stuff that I completely ignored it. Anyway, now when you tap on search bar on home screen it will take you to search screen instead of searching right there
