### ISSUE TITLE
Some youtube songs are not playing and moved to next song or stuck without starting.

### ISSUE THREAD

**Issue by Rahulremo2k** [Sangwan5688/BlackHole#660]
**Describe the bug**
A clear and concise description of what the bug is Some youtube songs are not playing and moved to next song or stuck without starting.

**Steps To Reproduce**
1. Go to Youtube section search for some random old songs.
2. Click on the song.
3. Play it.

**Expected behavior**
Resolve the bug to play those songs.

**Screenshots**

**Device Details (please complete the following information):**
 - OS: Android
 - Version: Android 12
 - Device: Samsung 
 - App Version: v1.15.8

**App Logs:**
Not available.

**Comment by Kurasami** [comment]
The app development was abandoned like a year ago: https://github.com/Sangwan5688/BlackHole/issues/344

**Comment by piotreknow02** [comment]
I believe this was fixed in version 1.15.9 which was published to IzzyOnDroid yeasterday. Had the same issue and it works fine today, so just try updating the app.

**Comment by OmarAMG** [comment]
Yo también tengo el mismo problema tengo la versión 1.15.9 y ciertas canciones agregadas a mi lista de reproducción con el tiempo dejan de funcionar, únicamente dejan de funcionar las canciones de Youtube y creo que únicamente sucede cuando las descargo

**Comment by Sangwan5688** [comment]
This has already been fixed in 1.15.9
