### ISSUE TITLE
Youtube seek bar

### ISSUE THREAD

**Issue by Shentia** [Sangwan5688/BlackHole#667]
**Describe the bug**
Hey team, I've noticed an issue. When a user selects music from "YouTube" and changes the Audio Repeat Mode to 'One', the seek bar doesn't restart once it reaches the end. Instead, the timer continues, and the seek bar becomes unresponsive. Has anyone else encountered this?

<img width="334" alt="Screenshot 2023-08-24 at 1 01 14 AM" src="https://github.com/Sangwan5688/BlackHole/assets/19757691/aedc1642-a5f6-4778-9fef-2a1c613a8490">

I didn't get any error on my log file also I am using iPhone 13 pro devices

**Comment by sharmaAshish-dev** [comment]
Hey there! I'd love to contribute and help address this issue. Let's work together to enhance the user experience. Feel free to let me know how I can assist!

**Comment by Shubh2003** [comment]
I want to contribute to this issue can you please assign this issue to me

**Comment by Shentia** [comment]
Fixed
