### ISSUE TITLE
when the current song is running/playing 

### ISSUE THREAD

**Issue by bilalmirza74** [Sangwan5688/BlackHole#668]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bilalmirza74** [comment]
when the current song is running if i click on previous button it's moving to the previous song instead of going to the previous song it should play the current song from starting and on second click on previous then it should move to the previous song.,  i.e my suggestion

**Comment by BrightDV** [comment]
It is already present.
Go to the settings > Music & Playback > Replay on Skip Previous

**Comment by bilalmirza74** [comment]
Ohhh
tq
