### ISSUE TITLE
Special characters the title cause an issue when downloading

### ISSUE THREAD

**Issue by CaptainKnox** [Sangwan5688/BlackHole#68]
Reopening to inform that full stops in the title also cause an issue. If you included that then go ahead and close this.

_Originally posted by @CaptainKnox in https://github.com/Sangwan5688/BlackHole/issues/67#issuecomment-879841251_

**Comment by Sangwan5688** [comment]
You could have re-opened the same issue. Anyway, I will add it

**Comment by CaptainKnox** [comment]
> You could have re-opened the same issue. Anyway, I will add it

Did not know how to. Sorry. Beta has solved it.

**Comment by Sangwan5688** [comment]
There is a button "Reopen" below the issue. You can use that. No worries :)

**Comment by CaptainKnox** [comment]
: is also causing issues
