### ISSUE TITLE
Importing music from Apple Music doesn't work

### ISSUE THREAD

**Issue by GuiFlam** [Sangwan5688/BlackHole#681]
**Describe the bug**

I am trying to import my music that is in Apple Music, the music is composed of 9 tracks. I want o import those tracks.

**Steps To Reproduce**

1. Go to My Music
2. It is loading infinitely

**Expected behavior**

Normally, my music is supposed to be imported in the app, however it doesn't seem to work. It just loads without anything else happening.

**Screenshots**

![image1](https://github.com/Sangwan5688/BlackHole/assets/113383738/98d97a3c-648c-4293-b2c6-e0cb0a867b2e)
As you can see, itunes music access is permitted.

![image0](https://github.com/Sangwan5688/BlackHole/assets/113383738/20c27f2e-518f-4b98-adbd-38ff5b899312)
When prompted for BlackHole to have access to my music, I said yes. It then loads without ever stopping.

[logs.txt](https://github.com/Sangwan5688/BlackHole/files/12615684/logs.txt)

**Comment by Sangwan5688** [comment]
Fixed with latest commit
