### ISSUE TITLE
Is the "Musix" yours

### ISSUE THREAD

**Issue by iamsdx** [Sangwan5688/BlackHole#684]
I found an app on Google Play, just the same as yours.
https://play.google.com/store/apps/details?id=com.spire.musix

**Comment by KillerDogeEmpire** [comment]
It's not his, if it was, it would have his github name, I know this since he's published apps to the playstore before @iamsdx

**Comment by Sangwan5688** [comment]
Nope, BlackHole is officially available only on our [Wesbite](https://sangwan5688.github.io/), [Github](https://github.com/Sangwan5688/BlackHole), [F-droid](https://f-droid.org/packages/com.shadow.blackhole/) & [IzzyDroid](https://android.izzysoft.de/repo/apk/com.shadow.blackhole) and with the name `BlackHole`, free of cost. If you see it anywhere else or any copy of it with any other name or any other developer claiming it to be his/her, or selling it online somewhere, you can just always report them.
