### ISSUE TITLE
Status bar icon color doesn't change instantly after switching theme into light mode

### ISSUE THREAD

**Issue by SaujanBindukar** [Sangwan5688/BlackHole#690]
In the setting/theme screen, when you change the theme from dark mode to light mode,  the icon color of the status bar doesn't change. It still remains white which is the same as in dark mode.

Expected:
Dark Mode => Color of the status bar icon should be white
Light Mode => Color of the status bar icon should be black

| <img src="https://github.com/Sangwan5688/BlackHole/assets/34705432/ae77058c-f3ed-4d0a-a743-ad3bbc578b8b" height="400" width="200">  | <img src="https://github.com/Sangwan5688/BlackHole/assets/34705432/fa7460aa-5df2-404f-9fdf-f7f386fa77d2" height="400" width="200"> |

**Comment by balogun14** [comment]
@SaujanBindukar can i be assigned to this issue i will like to solve it

**Comment by SaujanBindukar** [comment]
@balogun14  I have already solved this and created a PR #691

**Comment by balogun14** [comment]
@SaujanBindukar ohh okay thanks
