### ISSUE TITLE
RenderFlex Overflow on Small Screen Devices in the 'YouTube Home' screen & at Playlist Header

### ISSUE THREAD

**Issue by 0xAdiyat** [Sangwan5688/BlackHole#694]
## Description

When using the app on small-screen devices like the iPhone SE (3rd generation), an overflow issue occurs in the 'YouTube Home' screen. The specific error message displayed is as follows:
```markdown
======== Exception caught by rendering library =====================================================
The following assertion was thrown during layout:
A RenderFlex overflowed by 1.00 pixels on the right.
```

This is considered an error condition because it indicates that there is content that cannot be seen.
This overflow issue makes the app unusable on such devices and needs to be addressed.

### Steps To Reproduce

To reproduce the issue:

1. Launch the app on an iPhone SE (3rd generation) or a similar small-screen device.
2. Navigate to the 'YouTube Home' screen.
3. Observe the overflow error at the bottom right corner on "music for any mood title"

### Expected Behavior

The app should be able to render the 'YouTube Home' screen without any overflow issues on small-screen devices. Users should be able to use the app on these devices without encountering rendering errors.

### Screenshots

<img width="499" alt="image" src="https://github.com/Sangwan5688/BlackHole/assets/67780459/b439fce9-ba63-47bf-840d-3500a454050b">

### Device Details

- OS: iOS
- Version: iOS 17
- Device: iPhone SE (3rd generation)
- App Version: v1.15.9

### App Logs

```plaintext
======== Exception caught by rendering library =====================================================
The following assertion was thrown during layout:
A RenderFlex overflowed by 1.00 pixels on the right.

The relevant error-causing widget was: 
  Row Row:file:///Users/0xadiyat/Programming/GSOC/BlackHole/lib/Screens/YouTube/youtube_home.dart:191:27
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
```

### Additional Information

This issue is critical as it affects the usability of the app on small-screen iOS devices. Immediate attention is requested to resolve this issue.

**If it's okay then i'm up for it. It would be great if you can assign me with the task and let me resolve it. Thanks! :D**

**Comment by abhishek09827** [comment]
Hello @0xAdiyat pls assign this task to me, I have solved this issue

**Comment by 0xAdiyat** [comment]
> Hello @0xAdiyat pls assign this task to me, I have solved this issue

I also did mate, and was waiting for approval to get assigned from the maintainer.

**Comment by 0xAdiyat** [comment]
**Hey team, found another overflow error at playlist header screen.**

<img width="499" alt="image" src="https://github.com/Sangwan5688/BlackHole/assets/67780459/ab39b5d7-926e-4800-8797-b302d3a11a82">

To reproduce the issue:

1. Launch the app on an iPhone SE (3rd generation) or a similar small-screen device.
2. Navigate to any playlist.
3. Observe the overflow error at the bottom of play button.

**Comment by 0xAdiyat** [comment]
@abhishek09827 @yarons @hylau @nileshkinge sorry for the mention but it's fixed now.

<img width="455" alt="image" src="https://github.com/Sangwan5688/BlackHole/assets/67780459/5b15d5bb-6e63-4e1d-950a-d443843afe47">

**How about adding a tap feature to this text? When tapped, it would expand the text, allowing the user to see the full 'secondarySubtitle' if they wish?** 

<img width="137" alt="image" src="https://github.com/Sangwan5688/BlackHole/assets/67780459/b5997a8b-1459-4625-99e9-e3a229a83646">
