### ISSUE TITLE
feat: Add Auto Lyrics Scrolling Syncing Feature

### ISSUE THREAD

**Issue by 0xAdiyat** [Sangwan5688/BlackHole#699]
Auto lyrics scrolling syncing is a valuable feature that enhances the user experience of music players. It synchronizes the lyrics with the playing song, making it easier for users to sing along or follow along with the lyrics in real-time. I believe this feature would be a great addition to our project.

**Feature Request:** 

- [ ] Add the ability to sync lyrics with the currently playing song.
- [ ] Implement auto-scrolling of lyrics based on the current playback position.

**Expected Benefits:**

- Improved user engagement with music playback.
- Enhanced user experience, especially for karaoke enthusiasts.
- Attract more users to our music player.

Will I be working on this issue?
- [x] yes `if assigned`

**Comment by Dhanesh-Sawant** [comment]
Can I work on this issue..?

**Comment by 0xAdiyat** [comment]
> Can I work on this issue..?

Sorry, mate. I actually wanted to work on this issue.

**Comment by Dhanesh-Sawant** [comment]
okay np

**Comment by Sangwan5688** [comment]
BlackHole already support synced lyrics; it works only if you are logged in with Spotify though. You can check and if anything additional is required then work on that as well. Good Luck!

**Comment by Sangwan5688** [comment]
Closing this as it's already implemented. if you feel, they are limited to few songs, then you can try adding more sources.
