### ISSUE TITLE
Song restarts phone when  wakes from sleep

### ISSUE THREAD

**Issue by Gottarocket** [Sangwan5688/BlackHole#71]
**Describe the bug**
When the song is played it plays fine but when screen is turned off and when picked to check on song it starts from beginning h
**To Reproduce**
1. Go to 'blackhole'
2. Click on 'any song'
3. Let device turn off on same playlist open and then unlock device 
4. See song start from beginning

**Expected behavior**
Song should resume 
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 4]
 - OS: [e.g. Android 11]
 - App Version [e.g. v1.5]

**App Logs**
If possible please provide app logs here.

**Comment by Sangwan5688** [comment]
Ya it's because of the image slider on the play screen. I will fix it soon or I might even remove the image slider coz it's causing a lot of issues.

**Comment by Gottarocket** [comment]
Sure I am not sure if its related but many music players have that bug of not auto updating image based on song backend . I am checking on youtube end didnt open just loads will create new feature request as I prefer newpipe integration than directly to youtube or invidious instances. Anyway great work uninstalled amazon music for this

**Comment by Sangwan5688** [comment]
Well if it were just a normal image then it would be quite easy to manage it. But the images are inside a slider. Users can slide images to skip to songs. Coz of that slider it's difficult to keep them in sync and whenever it goes out of sync player thinks that you changed the image and starts playing that song causing that particular song to start again from start. As for the YouTube part, the home screen part sometimes doesn't load coz of youtube blocking the requests. But the search function does work all the time. Anyway, working on updates
