### ISSUE TITLE
Song does not play local music automatically after changing it via earphones button

### ISSUE THREAD

**Issue by akshinmustafayev** [Sangwan5688/BlackHole#72]
**Describe the bug**
Song does not play local music automatically after changing it via earphones button. 
After double press of earphones button, music switches to the next one but not plays automatically. To be able to listen the next song, you have to press button once.

**To Reproduce**
1. Find earphones with 3.5mm connector, which has integrated button on it. For example JBL In-ear headphones E15
2. Open local music list and play some music
3. Lock the phone
4. Double press earphones button

Note: Button double press does not work when phone is not in a locked state even, though it should

**Expected behavior**
Switch to the next local music and play it automatically

**Smartphone:**
 - Device: Xiaomi Mi Mix 3
 - OS: MIUI Global 12.0.2 Stable, Android 10 QKQ1.190828.002
 - App Version: v1.9.0

**Comment by Sangwan5688** [comment]
I have a few questions, will be glad if you can answer them.
1. It doesn't work only when the app is open? And is there a specific page? Like if doesn't work when the play screen is open and works for all other screens?
2. Is the issue only with local music?

**Comment by akshinmustafayev** [comment]
1. It doesn't work only when the app is open?


>  It doesn't work only when the app is open?
When I close the app, music stops playing automatically. Like application exit

> And is there a specific page? 
Described behavior is in all pages even if local music is playing in background

> Like if doesn't work when the play screen is open and works for all other screens?
It does not work, no matter what screen you open. 

The main point is that, when you start playing local music (does not matter which screen you open afterwards), and then lock the phone, music does not play automatically when you switch to the next one via headphones button via double-click. It is annoying when you put your phone into the pocket, and while walking, after switching music to the next one (by double-clicking), you have to press headphones button again third time to be able to listen the next music.

> Is the issue only with local music?
Most of the public music does not even play, and even in rare occasions when it does, double-click does not even change music to the next one.

Note: When you do not lock phone, and double-click headphones button, the next music even does not switch. It just pauses and unpauses fast

**Comment by Sangwan5688** [comment]
Ok, I will have a look.

**Comment by Sangwan5688** [comment]
The issue should be fixed with b95d00f. You can test beta if you want. Otherwise, you will be able to see changes in the next version.
