### ISSUE TITLE
BLACKHOLE FOR WINDoWS

### ISSUE THREAD

**Issue by Ajaythepower1606** [Sangwan5688/BlackHole#737]
HI , i am currently using the latest version on my android smart phone and loved the app .. so i searched for the pc version and i found one which was of old version v1.14.something ... if you have time please try to make the windows versions too of the latest version

**Comment by ShareASmile** [comment]
See this comment
https://github.com/Sangwan5688/BlackHole/issues/727#issuecomment-1799270708
