### ISSUE TITLE
How do I listen to music offline?

### ISSUE THREAD

**Issue by k0uu** [Sangwan5688/BlackHole#745]
as far as i know, if i download a song, it downloads internally to my phone, is there a way to download the song in the app like other music apps?

**Comment by SunPodder** [comment]
> is there a way to download the song in the app like other music apps?

Such that you can only access the songs through the app and not other apps? I guess that's not possible but you can change the download location

**Comment by Sangwan5688** [comment]
BlackHole downloads everything to external storage, you can still access songs from Blackhole or any other music player
