### ISSUE TITLE
Does Not work properly in Bluestacks

### ISSUE THREAD

**Issue by ntbk1919** [Sangwan5688/BlackHole#75]
**Describe the bug**
it gets stuck when clicking on another song while playing inside bluestacks

**To Reproduce**
1.Select a song to play
2. While it is playing,press back and select another song.
3.App gets stuck(freezes )

**Expected behavior**

![blstacks 1](https://user-images.githubusercontent.com/60788087/125775401-fda8f7f5-d0da-4c73-955c-b2eb0b9a86f3.png)
![bluestack2](https://user-images.githubusercontent.com/60788087/125775405-7a36b748-c58c-4f4b-930e-2d9518535471.png)
Play new song
**Screenshots**

**Smartphone (please complete the following information):**
 -Bluestacks emulator ,Oneplus 5

**App Logs**
If possible please provide app logs here.

**Comment by Sangwan5688** [comment]
Emulators like BlueStacks are different from physical devices. There can be a lot of reasons like network issues or memory issues. Please make sure that there are no such issues. Also, as far as the emulator is concerned, then the app does work on Android Emulators but third-party applications like BlueStacks are not tested. Please make sure there's no issue with your emulator.

**Comment by ntbk1919** [comment]
Vanced music works perfectly fine in this use case.
So,it's an issue with blackhole on bluestacks,albeit I'm unaware what the
exact issue is.
Since Windows 11 is also going to support Android directly,I thought this
would be an issue of interest.

**Comment by Sangwan5688** [comment]
Ok, I don't have bluestacks right now. I will test later and then let you know.

**Comment by ntbk1919** [comment]
Sure.

**Comment by Sangwan5688** [comment]
Sorry for being late; was busy with other stuff. So, the thing is, BlackHole runs fine of BlueStacks. I asked others for the same and got the answers stating everything is working fine. So, I assume the issue is maybe on your side. So, please make sure it's not because of your system.
Thanks for using the app :)
