### ISSUE TITLE
YT Music not downloading but showing in Files > BlackHole > Music

### ISSUE THREAD

**Issue by eTNTdiscord** [Sangwan5688/BlackHole#764]
**Describe the bug**
When I try to download a song from YT Music on Blackhole eg i need you by rage elixir (not on saavn), it is stuck on 100% and doesn’t download, but when I go to Files > On my iPad > Blackhole > Music it is showing the song but not showing in Downloads.

**Steps To Reproduce**
1. Go to 'Blackhole’
2. Search i need you by rage elixir on yt music (not there on saavn)
3. Click on song and song picture
4. press download
5. stuck on 100%

**Expected behavior**
Download the music and show in Downloads tab

**Screenshots**
![IMG_0635](https://github.com/Sangwan5688/BlackHole/assets/84364590/9e95cd10-e211-42d5-b3e4-0d9110a73db5)

**Device Details (please complete the following information):**
 - OS: iOS
 - Version: iOS 17
 - Device: iPad 9th gen
 - App Version: Latest [v1.15.10]

**App Logs:**

**Comment by eTNTdiscord** [comment]
@Sangwan5688

**Comment by adschfr** [comment]
I experience the same problem as well.
