### ISSUE TITLE
96kbps stream even when selecting 320kbps

### ISSUE THREAD

**Issue by BlueJeans7** [Sangwan5688/BlackHole#766]
The URL given in info always points to 96kbps stream even when you have selected to stream in 320kbps. If you download the file by copying the URL, it will download 96kbps. If you replace ‘96’ with ‘320’ in the URL, then it streams 320kbps.

Please check the screenshot showing URL.
![IMG_6004](https://github.com/Sangwan5688/BlackHole/assets/24786247/eddcd117-783b-42e8-b5a7-cc8ddb6d5b4e)

**Comment by Sangwan5688** [comment]
The url points to 96kbps only, but when playing the app automatically converts it to the URL according to your selected music quality in settings
