### ISSUE TITLE
App crash in iOS when hit Enter in keyboard.

### ISSUE THREAD

**Issue by girish54321** [Sangwan5688/BlackHole#78]
**Describe the bug**
App crash in iOS when hit Enter in keyboard same works in android

**To Reproduce**
1. Install iOS app
2. Enter you name
3. Hit Enter in Keyboard 

**Expected behavior**
It should go to Home screen. 

**Screenshots**
NA

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 14.5
 - App Version Newest

**App Logs**
NA

**Comment by Sangwan5688** [comment]
The app only supports Android devices as of now. I'm not sure how it works in iOS as I have never tested it there. So, any issue regarding the iOS side is basically not an issue coz it's not supported. I do have an issue open(#42). If you want to build the app for iOS you can help to do that. As far as Android is concerned, there's no such issue.

**Comment by girish54321** [comment]
Got it.
