### ISSUE TITLE
different song played when clicked on a particular song

### ISSUE THREAD

**Issue by bronze7** [Sangwan5688/BlackHole#786]
**Describe the bug**
This happens only on the favourites list. When clicked on a song, different song 3 or 4 songs down in the playlist is played instead.

**Steps To Reproduce**
1. Make a favourites playlist by clicking the heart button of any song
2. Go to the favourites playlist and click on any song

**Expected behavior**
It is expected to play that particular song which is clicked whereas a different song is played which is 3 or 4 songs down in the playlist. This never happens in other playlists like spotify imported ones or ones in discover.

**Device Details (please complete the following information):**
 - OS: Android
 - Version: 12
 - Device: Samsung Galaxy M51
 - App Version v1.15.0 universal

**App Logs:**

**Comment by GamingNerdLeith** [comment]
This happened to me but not with just favourites. Anytime I add a playlist and click on the song this bug happens.

**Comment by Sangwan5688** [comment]
Closing this as it has been fixed in latest beta
