### ISSUE TITLE
Songs do not download 

### ISSUE THREAD

**Issue by Justaregularguy00** [Sangwan5688/BlackHole#788]
**Describe the bug**
Song either gets stuck on 100% and won't download or download button and top part of the screen becomes grey and doesn't show in the downloads part of the app (Youtube songs)

**Steps To Reproduce**
Open app
download a song

**Expected behavior**
Song downloads and shows in download folder

**Screenshots**

**Device Details (please complete the following information):**
 - OS: IOS
-Version: IOS 15.7.1
 - Device: Iphone 12 mini
 - App Version 1.15.10
 - Installed with trollstore if that makes any difference

**Comment by Sangwan5688** [comment]
This has been fixed in the beta version, closing this
