### ISSUE TITLE
Home screen's "YouTube" tab not working

### ISSUE THREAD

**Issue by origamiofficial** [Sangwan5688/BlackHole#789]
**Describe the bug**
Whenever I click on the `YouTube` tab from BlackHole's home screen, it just keeps loading but I can search and play songs from both YT Music & YouTube fine. I've tried using VPN too.

**Steps To Reproduce**
1. Open BlackHole
2. Click on `YouTube` tab from bottom panel

**Expected behavior**
I had never used BlackHole before so I don't know what should appear here.

**Screenshots**
![Screenshot_20240113-042859](https://github.com/Sangwan5688/BlackHole/assets/64251776/6da8a0a6-3f31-4e19-bd8f-08d2da7248fe)

**Device Details (please complete the following information):**
 - OS: Android / iOS
 - Version: Android 14 / iOS 17.2
 - Device: Pixel 7 / iPhone 13 Pro Max
 - App Version: 1.15.10

**App Logs:**
[logs.txt](https://github.com/Sangwan5688/BlackHole/files/13924760/logs.txt)

**Comment by UserPendslol** [comment]
I also have this problem on iOS 16.6 iPhone 13

**Comment by nickf2k** [comment]
Anyone work on this? Can i try resolve

**Comment by origamiofficial** [comment]
This issue is fixed for me on v1.15.11-beta1

**Comment by Sangwan5688** [comment]
Closing this as this has been resolved in beta version. The issue was that youtube changed the schema a bit due to which it started breaking
