### ISSUE TITLE
Option to add favorite songs to my playlist

### ISSUE THREAD

**Issue by onlytanmoy** [Sangwan5688/BlackHole#80]
Title of this ticket basically :)

So in Library -> Favorites -> Songs when I click the 3 dots against a song, it will show me option to add to my Playlists. Currently it only shows remove option.

**Comment by Sangwan5688** [comment]
Well, "Favorite Songs" itself is a playlist, so there's no need to add it to playlists. You can access the favorites as a playlist by creating a new playlist with the name `Favorite Songs`. Anyway, I think there should be an option in playlists to add a song from one playlist to another. I will add one soon.

**Comment by onlytanmoy** [comment]
Thanks for the pointer on creating a playlist titled 'Favorite Songs' :) And yes that option will be cool.
