### ISSUE TITLE
I am getting this error while run the code (:app)

### ISSUE THREAD

**Issue by DivyBajpai** [Sangwan5688/BlackHole#802]
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'release' for SigningConfig container of type org.gradle.api.internal.FactoryNamedDomainObjectContainer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

**Comment by shrawank039** [comment]
Please confirm that you changed the release to debug in the 'app/build.gradle' file in the Android directory and removed the signingConfigs?


`    // remove signingConfigs when running debug version
//    signingConfigs {
//        release {
//            storeFile file(keystoreProperties['storeFile'])
//            storePassword keystoreProperties['storePassword']
//            keyAlias keystoreProperties['keyAlias']
//            keyPassword keystoreProperties['keyPassword']
//            v1SigningEnabled true
//            v2SigningEnabled true
//        }
//    }

    buildTypes {
        // replace release with "debug" when running on debug version
        debug {
            // TODO: Add your own signing config for the release build.
            // replace with "debug" when running on debug version
            signingConfig signingConfigs.debug
            shrinkResources false
        }`

**Comment by shrawank039** [comment]
**Please confirm that you removed/commented the signingConfigs & replaced release with 'debug' in 'app/build.gradle' file.**


 // remove signingConfigs when running debug version
    /*signingConfigs {
        release {
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }*/

    buildTypes {
        // replace release with "debug" when running on debug version
        debug {
            // TODO: Add your own signing config for the release build.
            // replace with "debug" when running on debug version
            signingConfig signingConfigs.debug
            shrinkResources false
        }
    }

**Comment by DivyBajpai** [comment]
[image: image.png]
This is my code I tried multiple times, but the same error is happening,
can you check it.

**Comment by shrawank039** [comment]
share your app/build.gradle file and please provide a detailed log.
