### ISSUE TITLE
[REQUEST]Flac streaming option

### ISSUE THREAD

**Issue by sahyam2019** [Sangwan5688/BlackHole#85]
If possible please add feature to stream songs in FLAC also.

**Comment by Sangwan5688** [comment]
I have received many requests regarding that, but I'm sorry it won't be possible. BlackHole does support offline FLAC, but as of now, it won't support FLAC streaming. I know there are some apps that use Deezer to provide FLAC support but I won't do anything like that. For normal users 320 kbps m4a is more than enough. Most streaming apps like iTunes, Spotify provide a max of 320 kbps. Going to FLAC will just cause an increase in size for most users. I might add FLAC in some unforeseen future but I don't have any plan to do so now. Sorry to all users who wanted FLAC streaming :(
And Thanks for using the App :)

**Comment by Sangwan5688** [comment]
I have received many requests regarding that, but I'm sorry it won't be possible. BlackHole does support offline FLAC, but as of now, it won't support FLAC streaming. I know there are some apps that use Deezer to provide FLAC support but I won't do anything like that. For normal users 320 kbps m4a is more than enough. Most streaming apps like iTunes, Spotify provide a max of 320 kbps. Going to FLAC will just cause an increase in size for most users. I might add FLAC in some unforeseen future but I don't have any plan to do so now. Sorry to all users who wanted FLAC streaming :(
And Thanks for using the App :)

**Comment by vehosah** [comment]
> 
> 
> I have received many requests regarding that, but I'm sorry it won't be possible. BlackHole does support offline FLAC, but as of now, it won't support FLAC streaming. I know there are some apps that use Deezer to provide FLAC support but I won't do anything like that. For normal users 320 kbps m4a is more than enough. Most streaming apps like iTunes, Spotify provide a max of 320 kbps. Going to FLAC will just cause an increase in size for most users. I might add FLAC in some unforeseen future but I don't have any plan to do so now. Sorry to all users who wanted FLAC streaming :(
> And Thanks for using the App :)

none all songs on jiosaavn are 320 m4a,half of them are 160,that means the 320 is a fat lie
