### ISSUE TITLE
Why bottombar hide when i go to new page.

### ISSUE THREAD

**Issue by pavelsust** [Sangwan5688/BlackHole#86]
I want that when I go to another page like song details BottomBar should not be hide. How I can implement that.

**Comment by girish54321** [comment]
This is normal behaviour in flutter
You can try this package 

https://t.co/Mta4Cjbj9L?amp=1

**Comment by Sangwan5688** [comment]
Well, the question is already answered. As described by @girish54321, it's the default behavior in flutter and is intentional.

**Comment by pavelsust** [comment]
@Sangwan5688  any option to keep it alive? I saw many application which have this feature.

**Comment by Sangwan5688** [comment]
You can implement one on your own if you want but as per BlackHole is concerned I won't add it.
