### ISSUE TITLE
Search History section inclusion

### ISSUE THREAD

**Issue by onlytanmoy** [Sangwan5688/BlackHole#87]
Hiya, so a "My search history" section on the left panel which will list all my search strings, basically it will retain my search history with the app. Clicking on one will trigger the search function.

**Comment by Sangwan5688** [comment]
There's already a search history and trending search option. Although it's still not available on the home screen. When you search from the search results screen, then you will be able to see that. I will do something about showing it on homescreen. There's already an open issue for that (#66).
