### ISSUE TITLE
Query regarding update

### ISSUE THREAD

**Issue by onlytanmoy** [Sangwan5688/BlackHole#88]
Hi mate, qq on update of the BlackHole app.
When I go to settings - About, its showing me v1.9.0. When I tap on it to check for updates, it says 'congrats! you are using the latest version'
But when I open F-Droid it says update available, shall I go ahead and do that via F-Droid? wanted to confirm with you as I don't want to screw up the working app :)

**Comment by Sangwan5688** [comment]
IzzyDroid shows "Update Available", coz you might have downloaded the app from the GitHub repo. If you download it from IzzyDroid itself then it won't show anything. Both versions are the same and you need not worry about that. As far as the update part is concerned, whenever a new update is available then you will be notified inside the app itself.

**Comment by onlytanmoy** [comment]
Ok cool, thanks for the clarification bud.

**Comment by Sangwan5688** [comment]
No Worries.
Keep Calm, open BackHole and listen to music :)
