### ISSUE TITLE
Unable to login into Spotify using google

### ISSUE THREAD

**Issue by No-obHub** [Sangwan5688/BlackHole#93]
**Describe the bug**
I'm not able to sign into my Spotify account using Google. When I try to sign in, I get an Authorisation Error (error 403)

**To Reproduce**
1. Go to the library tab
2. Tap on "Playlists"
3. Tap on "Import from Spotify" 
4. Tap on"Continue with Google" 
5. See error message

**Expected behavior**
I was supposed to sign into my Spotify account. 

**Screenshots**
![Screenshot_20210726-061058.jpg](https://user-images.githubusercontent.com/74432640/126979957-9386d08c-d183-41ca-80b6-81fecc13df74.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6t
 - OS: OxygenOS 10.3.10
 - App Version 1.9.0

**Comment by Sangwan5688** [comment]
Ya, Spotify login is done via webview which doesn't support all this as of now. I had plans to change it but there were some issues back then. I will try something else.

**Comment by No-obHub** [comment]
Sounds good 👍

**Comment by Sangwan5688** [comment]
Should be fixed with 45254f6
