### ISSUE TITLE
could replace the ext storage with some common component

### ISSUE THREAD

**Issue by jiangxiaoqiang** [Sangwan5688/BlackHole#94]
**Is your feature request related to a problem? Please describe.**

current the ext storage only support Android, in iOS, it could not work.

**Describe the solution you'd like**

replace storage with some common component should works in any platform, android, ios, pc, embbed.....

**Comment by Sangwan5688** [comment]
Well, I'm not familiar with any other package which might work in iOS. You can try using `Path Provider`. Path provider does provide an external storage path. But it's the app's external storage path. You might have to edit that path to get the actual external storage path. And I'm not sure even that is same for all iOS

**Comment by girish54321** [comment]
Hmm, I will check this for iOS.

**Comment by Sangwan5688** [comment]
As the ticket is related to iOS and is not really an issue for Android & Windows, I'm closing this. Any further discussion regarding this can be done within #42 which is better suited for this.

**Comment by aldocano** [comment]
@Sangwan5688 I will try to work with the project on the ios/mac side. Just cloned the repo and tried running the app and it is unable to play a song from the API and lags too much. 
I will try to investigate further and let you know in this thread.

**Comment by Sangwan5688** [comment]
@aldocano Thanks for that :)
Also, please use #42 instead, for anything related to iOS development.
