### ISSUE TITLE
Downloaded songs in the playlist are not shown.

### ISSUE THREAD

**Issue by Archonz-crazy** [Sangwan5688/BlackHole#95]
When we save a song in the playlist and download it, it is shown in the downloads section, but it is not shown as downloaded in playlist.

Expected behavior:
The song should be shown as downloaded in playlist and can be played offline.

Device: 
Samsung M21
Android 11

**Comment by Sangwan5688** [comment]
Inside BlackHole, the downloads and streaming are two different things. Unlike any other app BlackHole downloads songs in your external storage not inside the app's internal storage. As most streaming apps download inside the app itself it is easy for them to check if something is downloaded or not. Whereas it's not the same case for blackhole. Checking for a song if it's downloaded or not is a heavy task and will cause the app to lag. So, it's preferred this way and nothing can be done about that. If you try to download the same song again then it does shows the warning which is sufficient to prevent duplicates.

**Comment by Archonz-crazy** [comment]
Oh ok thanks 😁
