### ISSUE TITLE
Query on 'Add to Queue'

### ISSUE THREAD

**Issue by onlytanmoy** [Sangwan5688/BlackHole#96]
Hi mate, hope you doing fine. Just got a query on how the queue thing works.
I search for a song say A, go to the album say X and play it. While its playing I browse to a different album Y, click on 3 dots against a song say B and select 'Add to Queue', get the success message of song being added to queue.
But when the current song A stops playing, it does not play song B but some other song C from Album X.
What do I need to do to have B play up after A?

**Comment by Sangwan5688** [comment]
See when you play the song `A` from album `X`, then the whole album `X` loads. So it will contain let's say 10 songs. So, after `A` the next song in the album `X` is played. Now when you add the song `B`. It gets added at the end of the queue. So, that means it will be played after all 10 songs in album `X` have been played. One way you can change the sequence is by using now playing. There are two `Now Playing` sections, one in the library whereas other on the play screen. You can just drag-drop those songs to change the sequence. You can even swipe the songs to remove them from the queue.
Anyway I have plans to add an option `Play Next` along with `Add to Queue` for the same

**Comment by onlytanmoy** [comment]
Thanks for the nice explanation and the workaround on changing the play sequence.
+ 1 to your plan to add an option Play Next along with Add to Queue for the same
I will close this ticket now :)
