### ISSUE TITLE
Sleep Timer With "Close app after the number of songs"

### ISSUE THREAD

**Issue by ta1bbty** [Sangwan5688/BlackHole#99]
It would be great to have a sleep timer with sleep on the basis of no of songs 
**"Close app after the number of songs"**

![image](https://user-images.githubusercontent.com/45117337/128600116-79101cf2-5105-48d6-9736-da6bead3ab36.png)

**Comment by Sangwan5688** [comment]
Hmm sounds good. Will try to add it soon
